### ISSUE TITLE
Unexpected response code: 500 (CheckID does not have associated TTL)

### ISSUE THREAD

**Issue by huyifanstar** [joyent/containerpilot#254] opened 2016-11-29 04:38 UTC
help me ，kong and consul-server 
2016/11/29 04:24:16 [ERR] http: Request /v1/agent/check/pass/kong-8443-b0bc55df1f4c?note=ok, error: CheckID does not have associated TTL

**Comment by tgross** [comment] 2016-11-29 13:38
Dupe of https://github.com/joyent/containerpilot/issues/225, fixed in open PR https://github.com/joyent/containerpilot/pull/247

**Closed by tgross** 2016-11-29 13:38 UTC

**Comment by huyifanstar** [comment] 2016-11-29 14:32
This is what the problem
