### ISSUE TITLE
Allow preStart to set environment vars passed to application

### ISSUE THREAD

**Issue by BobDickinson** [joyent/containerpilot#205] opened 2016-08-10 23:39 UTC
It appears that ContainerPilot does not run the preStart script in the same environment that is uses to launch the app.  This prevents us from being able to set environment vars in preStart that the application can later access.

Our preStart collects some config data over the network and needs to get it to the app.  We can of course write the data to a file, though the app expects env vars and we'd prefer not to have to modify the app to pull from files instead (in this case and in general).

I think this is sort of related to #192, at least inasmuch as the workaround of having ContainerPilot run a launcher script, and having that script do whatever you would do in preStart and then run your app, is probably applicable.

But it would be a lot cleaner if preStart could just propagate env vars to the app (given that ContainerPilot is running the show).

**Comment by tgross** [comment] 2016-08-12 14:04
I like the idea but the mechanism to do so seems tricky.

Right now ContainerPilot only gets an exit code from all the various lifecycle hooks. Having the `preStart` provide more data back to ContainerPilot implies some kind of communication protocol between them which then `preStart` hooks would all have to implement.

One idea for how we could implement this without having some complicated communications channel is to have ContainerPilot load environment variables from its own config file. This way your `preStart` could render the environment you want to the the containerpilot.json file and then SIGHUP ContainerPilot to reload the config before continuing.

**Comment by BobDickinson** [comment] 2016-08-12 17:59
Well, I am not a Go programmer, so no guarantees that I'm following the code, but I was thinking something more along the lines of explicitly specifying the environment to both PreStartCmd and Command.  Right now that code appears to just use the default environment (presumably a copy of the system environment).  If you instantiate your own copy of os.Environ and pass that into PreStartCmd, and then also pass that same environment (potentially modified by PreStartCmd) into Command, I think that would accomplish what I was asking for.

**Comment by tgross** [comment] 2016-08-12 18:12
Right, and if the `preStart` was just a thread/goroutine in ContainerPilot then that would totally work.

But when we run the `preStart` command it fork/execs a new child process (the bash script or whatever you've specified). That child process automatically inherits the environment of its parent (ContainerPilot), but in Unix there's no way for a child process to change the environment of its parent without the parent co-operating by receiving messages via IPC/pipes/API call/etc.

So the problem isn't how do we get an environment into either `preStart` or the main application, but how we get the `preStart` process to communicate the changes back to its ContainerPilot parent.

**Comment by tgross** [comment] 2016-08-12 18:17
> without the parent co-operating by receiving messages via IPC/pipes/API call/etc.

I should probably point out here that there's been some discussion about whether ContainerPilot needs just such a control plane in https://github.com/joyent/containerpilot/issues/195.

**Comment by BobDickinson** [comment] 2016-08-12 18:47
OK, I see.  I didn't realize that all adding the Env to the Command does is initialize the new processes with those vars. 

I'm coming around to the idea that just doing this all in a startup script that's launched by ContainerPilot and that itself launches the app is probably the way to go for now.  But it would be great if there was a clean, easy way to do this at some point.

**Comment by tgross** [comment] 2016-08-12 18:56
> But it would be great if there was a clean, easy way to do this at some point.

Yeah, I agree. I'm going to keep this issue open so we can suss out what the right implementation should be.

**Comment by tgross** [comment] 2016-08-12 19:12
@BobDickinson I should point out here that you shouldn't try to have the `preStart` run your shimmed application, otherwise none of your health checks will be running. What you'll want to do instead is have ContainerPilot run a script that includes all the environment updates you need and then have that script run your application. So your Dockerfile might include:

```
CMD ["/usr/local/bin/containerpilot", "/usr/local/bin/start.sh"]
```

and then the `start.sh` script will be something like:

```bash
#!/bin/bash

get_config_data() {
  export KEY=$(/some/val/from/external/source)
  export OTHERKEY=$(/some/val/from/external/source)
}

get_config_data
/usr/local/bin/myApplication
```

You'll want to make sure you're trapping any signals your application needs so that they can be retransmitted too.

**Comment by BobDickinson** [comment] 2016-08-12 19:15
Thanks, that was my plan.  Though I hadn't considered passing signals.

**Comment by justenwalker** [comment] 2016-08-13 20:22
@BobDickinson - I'd like to point out also that your `/start.sh` script should always use `exec` to run the main application - otherwise it will not have any signals propagate:

*run.sh*:

```sh
...
get_config_data && exec /usr/local/bin/myApplication
```

**Comment by fitz123** [comment] 2016-08-22 14:49
If there any reason to use preStart script if "start.sh" is used as an application launcher?

**Comment by tgross** [comment] 2016-08-22 14:50
> If there any reason to use preStart script if "start.sh" is used as an application launcher?

One might want to modify the contents of `start.sh` at runtime.

**Comment by misterbisson** [comment] 2016-08-22 14:52
> If there any reason to use preStart script if "start.sh" is used as an application launcher?

It can sometimes be easier to strictly separate concerns. Doing the work that needs to be done to resolve application configuration in a `preStart` hook might be easier to manage and debug than combining it with a (hopefully very lightweight) script that injects configuration environment vars into the main process.

That said, the choice is up to you. ContainerPilot will trigger your executables, what you do with them is up to you.

**Comment by fitz123** [comment] 2016-08-22 14:58
@misterbisson, yeah, it's true. My question is mostly about "Best practices" here
@tgross, it's interesting, creates a workflow that totally could be useful. thanks for the idea

**Comment by tgross** [comment] 2016-11-17 21:13
https://github.com/joyent/containerpilot/issues/244 has been opened as a proposal to cover this issue as a 2.x-compatible enhancement.

**Comment by tgross** [comment] 2017-05-05 19:48
Merged in https://github.com/joyent/containerpilot/pull/339 and waiting pre-release.

**Comment by tgross** [comment] 2017-05-17 14:17
Pre-released in https://github.com/joyent/containerpilot/releases/tag/3.0.0-dev.3

**Closed by tgross** 2017-05-17 14:17 UTC
Labels: awaiting release, enhancement, v3.0.0
