### ISSUE TITLE
("preStop":"consul leave") does not work as expected, not sure what did I miss?

### ISSUE THREAD

**Issue by lmgnid** [joyent/containerpilot#278] opened 2017-02-09 07:07 UTC
Hello, I am using consul agent as co-process and ("preStop":"consul leave") works OK in other containers except one Nagios container:

THe only difference is that this main process "start_nagios" will start both nagios and apache but not only one application:
root@4e74221828bf:/# ps -ef | grep containerpilot | grep -v grep
root         1     0  0 Jan09 ?        00:00:00 /usr/local/bin/containerpilot /usr/local/bin/start_nagios

But as Containerpilot is still PID 1, not sure why ("preStop":"consul leave")  cannot trigged by "docker stop" with "SIGTERM", I also added (trap "/usr/local/bin/consul leave; exit" SIGTERM SIGHUP SIGINT) in (start_nagios) script but it is the same.

Not sure what did I miss, might be simple but just confused me right now. Thanks!

**Comment by tgross** [comment] 2017-02-09 13:25
> I also added (trap "/usr/local/bin/consul leave; exit" SIGTERM SIGHUP SIGINT) in (start_nagios) script but it is the same

That's interesting and suggests that `consul leave` is taking more time to complete than the timeout before Docker (or ContainerPilot) give up and SIGKILL the command process. Do you have DEBUG logs from this? That code path is pretty well instrumented so we might be able to figure out where it's getting hung-up.

On the SIGTERM happy path we should be seeing logs resembling this:

```
2017-02-09T13:24:19Z [INFO]: Deregistering service apache
2017-02-09T13:24:20Z [INFO]: Deregistering service nagios
2017-02-09T13:24:21Z [DEBUG]: PreStop.RunAndWait start
2017-02-09T13:24:21Z [DEBUG]: PreStop.Cmd.Run
2017-02-09T13:24:22Z [DEBUG]: PreStop.RunAndWait end
2017-02-09T13:24:22Z [INFO]: Killing Process start_nagios{}
```

Also can you provide the output of `containerpilot -version` for me?

> THe only difference is that this main process "start_nagios" will start both nagios and apache but not only one application

Just FYI, you probably want the nagios agent to be another co-process rather than wrapped in a shell script like this.

**Comment by lmgnid** [comment] 2017-02-09 23:52
Thanks for the reply, my containerpilot version is 2.6.0. It seems the issue is not caused by the SIGKILL but from the coprocesses ("restarts": "unlimited") settings for consul agent, if I set to ("restarts": "never"), the "consul leave" works OK.

Not sure if we can add the wait time setting for coprocesses restart? 

FYI, debug logs from ("restarts": "never"):

`2017/02/09 22:41:21 Deregistering service: nagios
2017/02/09 22:41:21     2017/02/09 22:41:21 [INFO] agent: Deregistered service 'nagios-4e74221828bf'
2017/02/09 22:41:21     2017/02/09 22:41:21 [INFO] agent: Deregistered check 'nagios-4e74221828bf'
2017/02/09 22:41:21 preStop.RunAndWait start
2017/02/09 22:41:21 preStop.Cmd.Run
2017/02/09 22:41:21     2017/02/09 22:41:21 [INFO] agent.rpc: Accepted client: 127.0.0.1:59932
2017/02/09 22:41:21     2017/02/09 22:41:21 [INFO] agent.rpc: Graceful leave triggered
2017/02/09 22:41:21     2017/02/09 22:41:21 [INFO] consul: client starting leave
2017/02/09 22:41:22     2017/02/09 22:41:22 [INFO] serf: EventMemberLeave: 4e74221828bf 172.19.0.163
2017/02/09 22:41:22     2017/02/09 22:41:22 [INFO] agent: requesting shutdown
2017/02/09 22:41:22     2017/02/09 22:41:22 [INFO] consul: shutting down client
2017/02/09 22:41:22 Graceful leave complete
2017/02/09 22:41:22     2017/02/09 22:41:22 [INFO] manager: shutting down
2017/02/09 22:41:22     2017/02/09 22:41:22 [INFO] agent: shutdown complete
2017/02/09 22:41:22 preStop.RunAndWait end
Shutting Down
2017/02/09 22:41:22 coprocess[/usr/local/bin/consul agent -data-dir=/var/lib/consul -config-dir=/etc/consul -rejoin -retry-join consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com -retry-max 10 -retry-interval 10s].RunAndWait end
2017/02/09 22:41:22 coprocess[/usr/local/bin/consul agent -data-dir=/var/lib/consul -config-dir=/etc/consul -rejoin -retry-join consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com -retry-max 10 -retry-interval 10s] exited
Caught SIGTERM, shutting down...
Successfully shutdown... (PID=63726)
ok: down: apache: 0s, normally up
ok: down: nagios: 0s, normally up
ok: down: postfix: 0s, normally up
2017/02/09 22:41:26 <nil>
`
And debug logs from ("restarts": "unlimited"):

`2017/02/09 22:44:19 Deregistering service: nagios
2017/02/09 22:44:19     2017/02/09 22:44:19 [INFO] agent: Deregistered service 'nagios-4e74221828bf'
2017/02/09 22:44:19     2017/02/09 22:44:19 [INFO] agent: Deregistered check 'nagios-4e74221828bf'
2017/02/09 22:44:19 preStop.RunAndWait start
2017/02/09 22:44:19 preStop.Cmd.Run
2017/02/09 22:44:19     2017/02/09 22:44:19 [INFO] agent.rpc: Accepted client: 127.0.0.1:65278
2017/02/09 22:44:19     2017/02/09 22:44:19 [INFO] agent.rpc: Graceful leave triggered
2017/02/09 22:44:19     2017/02/09 22:44:19 [INFO] consul: client starting leave
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberLeave: 4e74221828bf 172.19.0.163
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] agent: requesting shutdown
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] consul: shutting down client
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] manager: shutting down
2017/02/09 22:44:20 Graceful leave complete
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] agent: shutdown complete
2017/02/09 22:44:20 preStop.RunAndWait end
Shutting Down
2017/02/09 22:44:20 coprocess[/usr/local/bin/consul agent -data-dir=/var/lib/consul -config-dir=/etc/consul -rejoin -retry-join consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com -retry-max 10 -retry-interval 10s].RunAndWait end
2017/02/09 22:44:20 coprocess[/usr/local/bin/consul agent -data-dir=/var/lib/consul -config-dir=/etc/consul -rejoin -retry-join consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com -retry-max 10 -retry-interval 10s] exited
2017/02/09 22:44:20 coprocess[/usr/local/bin/consul agent -data-dir=/var/lib/consul -config-dir=/etc/consul -rejoin -retry-join consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com -retry-max 10 -retry-interval 10s].RunAndWait start
2017/02/09 22:44:20 coprocess[/usr/local/bin/consul agent -data-dir=/var/lib/consul -config-dir=/etc/consul -rejoin -retry-join consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com -retry-max 10 -retry-interval 10s].Cmd.Run
2017/02/09 22:44:20 ==> Starting Consul agent...
2017/02/09 22:44:20 ==> Starting Consul agent RPC...
2017/02/09 22:44:20 ==> Consul agent running!
2017/02/09 22:44:20            Version: 'v0.7.0'
2017/02/09 22:44:20          Node name: '4e74221828bf'
2017/02/09 22:44:20         Datacenter: 'dc1'
2017/02/09 22:44:20             Server: false (bootstrap: false)
2017/02/09 22:44:20        Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
2017/02/09 22:44:20       Cluster Addr: 172.19.0.163 (LAN: 8301, WAN: 8302)
2017/02/09 22:44:20     Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
2017/02/09 22:44:20              Atlas: <disabled>
2017/02/09 22:44:20
2017/02/09 22:44:20 ==> Log data will now stream in as it occurs:
2017/02/09 22:44:20
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Ignoring previous leave in snapshot
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 4e74221828bf 172.19.0.163
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Attempting re-join to previously known node: 6fbc6bfb6c1b: 172.19.0.174:8301
2017/02/09 22:44:20     2017/02/09 22:44:20 [WARN] manager: No servers available
2017/02/09 22:44:20     2017/02/09 22:44:20 [ERR] agent: failed to sync remote state: No known Consul servers
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] agent: Joining cluster...
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] agent: (LAN) joining: [consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com]
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 6cc35ad3fd25 172.19.0.65
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: f6acf9ed7f5c 172.19.0.61
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: f818878b36c0 172.19.0.62
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 70af851359e1 172.19.0.72
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 33a4ee7ba76f 172.19.0.158
2017/02/09 22:44:20     2017/02/09 22:44:20 [WARN] memberlist: Refuting a suspect message (from: 4e74221828bf)
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 0541d7cf932c 172.19.0.70
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 76afb51d9a15 172.19.0.69
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 6fbc6bfb6c1b 172.19.0.174
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: f947f1b94cb2 172.19.0.64
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: aa5a5092a556 172.19.0.162
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: f4d695470edf 172.19.0.159
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 5b6f6dd58e8d 172.19.0.157
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: cec42c7e11e4 172.19.0.63
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 740714d6a247 172.19.0.68
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] consul: adding server f6acf9ed7f5c (Addr: tcp/172.19.0.61:8300) (DC: dc1)
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 169e0a6b1339 172.19.0.85    2017/02/09 22:44:20 [INFO] consul: adding server f818878b36c0 (Addr: tcp/172.19.0.62:8300) (DC: dc1)
2017/02/09 22:44:20
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 9934411f63dd 172.19.0.60
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 928857030497 172.19.0.161
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 6b2245bfc209 172.19.0.73
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 8429a6162044 172.19.0.160
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 2db85d47a6f7 172.19.0.67
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 47d0d5a16331 172.19.0.71
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: 76668ac33280 172.19.0.74
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: EventMemberJoin: faf9fd2d85a1 172.19.0.156
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] serf: Re-joined to previously known node: 6fbc6bfb6c1b: 172.19.0.174:8301
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] consul: adding server 9934411f63dd (Addr: tcp/172.19.0.60:8300) (DC: dc1)
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] agent: (LAN) joined: 3 Err: <nil>
2017/02/09 22:44:20     2017/02/09 22:44:20 [INFO] agent: Join completed. Synced with 3 initial agents
Caught SIGTERM, shutting down...
Successfully shutdown... (PID=68744)
ok: down: apache: 0s, normally up
ok: down: nagios: 0s, normally up
ok: down: postfix: 0s, normally up
2017/02/09 22:44:22     2017/02/09 22:44:22 [INFO] agent: Synced node info
2017/02/09 22:44:24 <nil>
`

**Comment by tgross** [comment] 2017-02-10 15:00
> Thanks for the reply, my containerpilot version is 2.6.0. It seems the issue is not caused by the SIGKILL but from the coprocesses ("restarts": "unlimited") settings for consul agent, if I set to ("restarts": "never"), the "consul leave" works OK.

I agree with your assessment of the logs. From the [docs for `consul leave`:](https://www.consul.io/docs/commands/leave.html)
> The leave command triggers a graceful leave and shutdown of the agent.

And unfortunately the HTTP API is exactly the same behavior: https://www.consul.io/docs/agent/http/agent.html#agent_leave

So what's happening is that ContainerPilot sees that we've terminated the application and says "hey you wanted me to restart this" when what we really want is for Consul Agent to leave the cluster but then be shut down by ContainerPilot sending "stop". If this were the "main" process then we could put it into maintenance mode first, but there's currently no way to communicate to ContainerPilot that a coprocess is being shut down externally.

> Not sure if we can add the wait time setting for coprocesses restart?

Ultimately this will be fixed by the [proposal for multi-process handling](https://github.com/joyent/rfd/blob/4b6c69b42cf6833f177826d9a30e14c6ad5cb42c/rfd/0086/multiprocess.md) in [RFD86 (ContainerPilot 3)](https://github.com/joyent/rfd/pull/13) by having each process have its own chain of dependencies.

In the meantime, you should probably have your Consul agent configured with [`leave_on_terminate`](https://www.consul.io/docs/agent/options.html#leave_on_terminate) which will accomplish what you're trying to do without involving the order-of-operations problem of `preStop`.

**Comment by lmgnid** [comment] 2017-02-10 18:53
Hi Tim, yes good to know we have a long term solution in RFD86.

"leave_on_terminate" is the default setting for Consul agent, we tested and it will deregistered the  service and check, but not for "node", so a critical "node" will still be left.

So I can see 2 workaround for this right now:
- For not so critical service like Nagios, I can use "("restarts": "never")
- Or If the main application can be stoped very quick before the consul agent restart, we can hop the consul agent will not re-register again.

Please also suggest if you have other better ideas. Thanks!

**Comment by tgross** [comment] 2017-02-10 19:12
> "leave_on_terminate" is the default setting for Consul agent, we tested and it will deregistered the service and check, but not for "node", so a critical "node" will still be left

The [`leave_on_terminate` docs](https://www.consul.io/docs/agent/options.html#leave_on_terminate) seem to suggest that's the wrong behavior:
> If enabled, when the agent receives a TERM signal, it will send a Leave message to the rest of the cluster and gracefully leave.

I wonder if you're seeing the node left behind because the agent is getting the leave instruction before the service deregistration can be gossiped to other nodes? When you're seeing this, is the service still visible (and Critical, probably) in the Consul UI? 

If so, is this a problem right away or is it just a problem with cleaning up noise in Consul? If the latter, you might want to add the `deregisterCriticalServiceAfter ` field to your ContainerPilot service config so that they get cleaned up automatically.

**Comment by lmgnid** [comment] 2017-02-10 20:01
I tried both ("leave_on_terminate": true) in consul.json, plus ("deregisterCriticalServiceAfter": "1m"), but still have the zombie nodes left after 1m, but the "nagios" service was removed. From the log (without  "preStop":"consul leave") bellow, it only Deregister servie and check sucessfully:

2017/02/10 19:45:41 Deregistering service: nagios
2017/02/10 19:45:41     2017/02/10 19:45:41 [INFO] agent: Deregistered service 'nagios-4e74221828bf'
2017/02/10 19:45:41     2017/02/10 19:45:41 [INFO] agent: Deregistered check 'nagios-4e74221828bf'
Shutting Down
Caught SIGTERM, shutting down...
Successfully shutdown... (PID=71781)
ok: down: apache: 0s, normally up
ok: down: nagios: 0s, normally up
ok: down: postfix: 0s, normally up
2017/02/10 19:45:45 <nil>

If I add the ("preStop":"consul leave") again, will still have the zombie node left. So it should not be a consul sync issues.

**Comment by uslava77** [comment] 2017-02-10 22:55
I was looking at this: https://github.com/joyent/containerpilot/blob/master/core/app.go
And noticed something that might be related to this issue.

The only time stopCoprocesses is called is in the function Reload (line 299), but only in the function coprocess.Stop is the restart bool set to false (stops the coprocess from restarting I'm guessing?). So when the app is terminated, Terminate function runs, but stopCoprocesses is not called inside it so restart may be true. Is this expected behavior? Should terminate not also stop the coprocesses or is this already implemented and I just missed it?

Thanks

**Comment by tgross** [comment] 2017-02-13 13:56
> I tried both ("leave_on_terminate": true) in consul.json, plus ("deregisterCriticalServiceAfter": "1m"), but still have the zombie nodes left after 1m, but the "nagios" service was removed. From the log (without "preStop":"consul leave") bellow, it only Deregister servie and check sucessfully:

This looks like you turned off debug logging again, which really helps to dig into this. But this is without the `preStop` but with the `leave_on_terminate`? I don't see any Consul Agent logs in this log at all.

>  Should terminate not also stop the coprocesses or is this already implemented and I just missed it?

This is intentional. If we stop coprocesses before `preStop` then `preStop` and `postStop` won't have access to whatever coprocesses we were running. Given that the initial use case for coprocess was for Consul Agent, changing this would potentially break any `preStop` or `postStop` that require the agent. (For example, a database might back itself up during `preStop` and write the location of the backup to Consul.) This sequence isn't something we'll be able to change until we do ContainerPilot 3. Please feel free to give your comments in https://github.com/joyent/rfd/pull/13!

That being said, I think we could safely add a call to `stopCoprocesses` immediately before this line: https://github.com/joyent/containerpilot/blob/master/core/app.go#L191. This shouldn't break any existing applications. I'd be happy to accept a PR (with tests!) for this.

**Comment by lmgnid** [comment] 2017-02-16 00:13
@tgross : Bellow is the debug logs for "docker stop", this config has ("leave_on_terminate": true) in consul.json, plus ("deregisterCriticalServiceAfter": "1m") in container pilot "services", without ("preStop":"consul leave") but has ("restarts": "unlimited") for consul agent coprocess.

Not sure if it is helpful. Same as before, the service was deregistered but the "zombie" node still left.

2017/02/16 00:03:35 nagios.health.RunWithTimeout start
2017/02/16 00:03:35 nagios.health.Cmd.Start
2017/02/16 00:03:35 nagios.health.run waiting for PID 37874:
2017/02/16 00:03:36 NAGIOS OK: 51 processes, status log updated 1 second ago
2017/02/16 00:03:36 nagios.health.run complete
2017/02/16 00:03:36 nagios.health.RunWithTimeout end
2017/02/16 00:03:36     2017/02/16 00:03:36 [DEBUG] agent: Check 'nagios-f53a100ed401' status is now passing
2017/02/16 00:03:36     2017/02/16 00:03:36 [DEBUG] agent: Service 'nagios-f53a100ed401' in sync
2017/02/16 00:03:36     2017/02/16 00:03:36 [DEBUG] agent: Check 'nagios-f53a100ed401' in sync
2017/02/16 00:03:36     2017/02/16 00:03:36 [DEBUG] agent: Node info in sync
2017/02/16 00:03:36     2017/02/16 00:03:36 [DEBUG] http: Request PUT /v1/agent/check/pass/nagios-f53a100ed401?note=ok (594.556ÃÂµs) from=127.0.0.1:43582017/02/16 00:03:40 Deregistering service: nagios
2017/02/16 00:03:40     2017/02/16 00:03:40 [INFO] agent: Deregistered service 'nagios-f53a100ed401'
2017/02/16 00:03:40     2017/02/16 00:03:40 [INFO] agent: Deregistered check 'nagios-f53a100ed401'
2017/02/16 00:03:40     2017/02/16 00:03:40 [DEBUG] agent: Node info in sync
2017/02/16 00:03:40     2017/02/16 00:03:40 [DEBUG] http: Request PUT /v1/agent/service/deregister/nagios-f53a100ed401 (7.854936ms) from=127.0.0.1:43583
2017/02/16 00:03:40     2017/02/16 00:03:40 [DEBUG] agent: Node info in sync
2017/02/16 00:03:40     2017/02/16 00:03:40 [DEBUG] agent: Node info in sync
Shutting Down
Caught SIGTERM, shutting down...
Successfully shutdown... (PID=37408)
ok: down: apache: 0s, normally up
ok: down: nagios: 1s, normally up
2017/02/16 00:03:41     2017/02/16 00:03:41 [DEBUG] memberlist: TCP connection from=172.19.0.235:57898
ok: down: postfix: 1s, normally up
2017/02/16 00:03:43 ==> Caught signal: terminated
2017/02/16 00:03:43 ==> Gracefully shutting down agent...
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] consul: client starting leave
2017/02/16 00:03:43 <nil>
2017/02/16 00:03:43 coprocess[/usr/local/bin/consul agent -datacenter=us-east-1 -data-dir=/var/lib/consul -config-dir=/etc/consul -rejoin -retry-join consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com -retry-max 10 -retry-interval 10s] exited
2017/02/16 00:03:43 coprocess[/usr/local/bin/consul agent -datacenter=us-east-1 -data-dir=/var/lib/consul -config-dir=/etc/consul -rejoin -retry-join consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com -retry-max 10 -retry-interval 10s].RunAndWait start
2017/02/16 00:03:43 coprocess[/usr/local/bin/consul agent -datacenter=us-east-1 -data-dir=/var/lib/consul -config-dir=/etc/consul -rejoin -retry-join consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com -retry-max 10 -retry-interval 10s].Cmd.Run
2017/02/16 00:03:43 ==> Starting Consul agent...
2017/02/16 00:03:43 ==> Starting Consul agent RPC...
2017/02/16 00:03:43 ==> Consul agent running!
2017/02/16 00:03:43            Version: 'v0.7.0'
2017/02/16 00:03:43          Node name: 'f53a100ed401'
2017/02/16 00:03:43         Datacenter: 'us-east-1'
2017/02/16 00:03:43             Server: false (bootstrap: false)
2017/02/16 00:03:43        Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
2017/02/16 00:03:43       Cluster Addr: 172.19.0.226 (LAN: 8301, WAN: 8302)
2017/02/16 00:03:43     Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
2017/02/16 00:03:43              Atlas: <disabled>
2017/02/16 00:03:43
2017/02/16 00:03:43 ==> Log data will now stream in as it occurs:
2017/02/16 00:03:43
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: Ignoring previous leave in snapshot
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: Ignoring previous leave in snapshot
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: Ignoring previous leave in snapshot
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: Ignoring previous leave in snapshot
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: Ignoring previous leave in snapshot
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: Ignoring previous leave in snapshot
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: f53a100ed401 172.19.0.226
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: Attempting re-join to previously known node: 4c03d43bcde6: 172.19.0.223:8301
2017/02/16 00:03:43     2017/02/16 00:03:43 [DEBUG] memberlist: Initiating push/pull sync with: 172.19.0.223:8301
2017/02/16 00:03:43     2017/02/16 00:03:43 [WARN] manager: No servers available
2017/02/16 00:03:43     2017/02/16 00:03:43 [ERR] agent: failed to sync remote state: No known Consul servers
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] agent: Joining cluster...
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] agent: (LAN) joining: [consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com]
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: fc7bbc824cbd 172.19.0.231
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: b9311c0d79fd 172.19.0.222
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: d388a90cf925 172.19.0.234
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: 8e114ee0a1f9 172.19.0.236
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: 2f02d946ec95 172.19.0.220
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: 4c03d43bcde6 172.19.0.223
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: a1bbf153a2bc 172.19.0.218
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: 446991d01ece 172.19.0.228
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: 1638f6cdcdca 172.19.0.224
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: f0bac891c2f4 172.19.0.235
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: e8f6fb9c3eae 172.19.0.215
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: bf6a6c9c6865 172.19.0.217
2017/02/16 00:03:43     2017/02/16 00:03:43 [WARN] memberlist: Refuting an alive message
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: 1ce89d582075 172.19.0.238
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: EventMemberJoin: e82a330db0b8 172.19.0.225
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] serf: Re-joined to previously known node: 4c03d43bcde6: 172.19.0.223:8301
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] consul: adding server a1bbf153a2bc (Addr: tcp/172.19.0.218:8300) (DC: us-east-1)
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] consul: adding server e8f6fb9c3eae (Addr: tcp/172.19.0.215:8300) (DC: us-east-1)
2017/02/16 00:03:43     2017/02/16 00:03:43 [INFO] consul: adding server bf6a6c9c6865 (Addr: tcp/172.19.0.217:8300) (DC: us-east-1)
2017/02/16 00:03:43 <nil>

**Comment by tgross** [comment] 2017-02-17 14:00
This line shows the problem: the coprocess should not be restarting at all in this case.
```
2017/02/16 00:03:43 coprocess[/usr/local/bin/consul agent -datacenter=us-east-1 -data-dir=/var/lib/consul -config-dir=/etc/consul -rejoin -retry-join consul.svc.e14c2413-7179-44f8-dfc3-b8624dcb10bb.us-east-1.cns.joyent.com -retry-max 10 -retry-interval 10s].RunAndWait start
```

This seems like a bug, but I wonder if this problem would be fixed by https://github.com/joyent/containerpilot/pull/198 if we could get that tested and merged in.

**Comment by sberryman** [comment] 2017-04-07 18:54
I'm also experiencing this issue, would be great to have a solution for v2. In fact, all the autopilotpattern examples using `CONSUL_AGENT=1` have the issue of leaving the node behind on container termination.

**Comment by tgross** [comment] 2017-06-19 20:37
So I've circled back to this and I'm unable to reproduce what we're seeing here with ContainerPilot 2.7.4 and Consul 0.8.4 in the container when using a `postStop` field that says to do a `consul leave`. Removing this field leaves behind the node as expected.

If we can create a minimal reproduction and trace it to particular versions of Consul, then we should probably do so and update the various Autopilot Pattern blueprints to make sure we're using whatever minimum version we discover there as required. 

But in the meantime I'm going to close this, as it doesn't appear to be a ContainerPilot issue per se.

---

My Dockerfile:

```
FROM alpine:latest

RUN apk --no-cache add curl

ENV CONSUL_VERSION=0.8.4
RUN export CONSUL_CHECKSUM=c8859a0a34c50115cdff147f998b2b63226f5f052e50f342209142420d1c2668 \
    && export archive=consul_${CONSUL_VERSION}_linux_amd64.zip \
    && curl -Lso /tmp/${archive} https://releases.hashicorp.com/consul/${CONSUL_VERSION}/${archive} \
    && echo "${CONSUL_CHECKSUM}  /tmp/${archive}" | sha256sum -c \
    && cd /bin \
    && unzip /tmp/${archive} \
    && chmod +x /bin/consul \
    && rm /tmp/${archive}

ENV CONTAINERPILOT_VER 2.7.4
ENV CONTAINERPILOT file:///containerpilot.json

RUN export CONTAINERPILOT_CHECKSUM=073b7bc987f7bf0ca92ae5531d7df6eb02e31bfa \
    && curl -Lso /tmp/containerpilot.tar.gz \
    "https://github.com/joyent/containerpilot/releases/download/${CONTAINERPILOT_VER}/containerpilot-${CONTAINERPILOT_VER}.tar.gz" \
    && echo "${CONTAINERPILOT_CHECKSUM}  /tmp/containerpilot.tar.gz" | sha1sum -c \
    && tar zxf /tmp/containerpilot.tar.gz -C /bin \
    && rm /tmp/containerpilot.tar.gz

COPY containerpilot.json /containerpilot.json
CMD /bin/containerpilot -version
```

My docker-compose configuration:

```yaml
version: '2.1'

services:

  consul:
    image: autopilotpattern/consul:0.7.2-r0.8
    container_name: consul
    ports:
      - 8500:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    network_mode: bridge
    command: >-
      /usr/local/bin/containerpilot
      /bin/consul agent -server
        -bootstrap-expect 1
        -config-dir=/etc/consul
        -ui-dir=/ui

  leaver:
    build: .
    container_name: leaver
    links:
      - consul:consul
    volumes:
      - ./containerpilot.json:/containerpilot.json
      - ./consul.json:/consul.json
    command: /bin/containerpilot sleep 30
    network_mode: bridge
```

My ContainerPilot configuration:

```json
{
  "consul": "localhost:8500",
  "logging": {
    "level": "DEBUG"
  },
  "services": [
    {
      "name": "leaver",
      "health": "true",
      "port": 8000,
      "poll": 1,
      "ttl": 5
    }
  ],
  "postStop": "consul leave",
  "coprocesses": [
    {
      "command": "consul agent -config-file=/consul.json",
      "restarts": "unlimited"
    }
  ]
}
```

My /consul.json in the "leaver" container:

```json
{
  "data_dir": "/data",
  "ui_dir": "/ui",
  "rejoin_after_leave": true,
  "retry_join": ["consul"],
  "retry_max": 10,
  "retry_interval": "3s",
  "leave_on_terminate": true
}
```

**Closed by tgross** 2017-06-19 20:37 UTC
Labels: usage, v2
