### ISSUE TITLE
Job's health always report UNKNOWN

### ISSUE THREAD

**Issue by ramitos** [joyent/containerpilot#445] opened 2017-07-25 12:38 UTC
> what is happening and what you expect to see

Job's health always report UNKNOWN

> the output of `containerpilot -version`

```
λ docker exec -it 019b5cb7fe1f bash
bash-4.3# containerpilot -version
Version: 3.2.0
GitHash: e2fb5ec
```

- the ContainerPilot configuration you're using
https://gist.github.com/ramitos/9a1bb632d637d9236f21baf9b78bdeff

- the output of any logs you can share; if you can it would be very helpful to turn on debug logging by adding `logging: { level: "DEBUG"}` to your ContainerPilot configuration.

```
λ docker logs 019b5cb7fe1f       
2017-07-25T12:32:19.131284071Z control: serving at /var/run/containerpilot.socket
2017-07-25T12:32:19.146869914Z telemetry: serving at 
2017-07-25T12:32:19.338510289Z ==> Starting Consul agent...
2017-07-25T12:32:19.391809718Z ==> Consul agent running!
2017-07-25T12:32:19.392872395Z     2017/07/25 12:32:19 [ERR] agent: failed to sync remote state: No known Consul servers
2017-07-25T12:32:20.157763994Z check.frontend exited with error: check.frontend: exit status 7
2017-07-25T12:32:20.323644347Z Listening on http://0.0.0.0:3030
2017-07-25T12:32:20.606477344Z ==> Newer Consul version available: 0.9.0 (currently running: 0.8.5)
2017-07-25T12:32:21.152725649Z 1500985941152 got req
2017-07-25T12:32:22.152082966Z 1500985942151 got req
2017-07-25T12:32:23.149841508Z 1500985943149 got req
2017-07-25T12:32:24.151038834Z 1500985944150 got req
```

```
λ docker exec -it 019b5cb7fe1f bash
bash-4.3# curl -o /dev/null --fail -s http://localhost:3030/  
bash-4.3# echo $?
0
bash-4.3# curl http://165.225.128.237:9090/status  
{
  "Version": "3.2.0",
  "Services": [
    {
      "Name": "frontend",
      "Address": "192.168.130.164",
      "Port": 3030,
      "Status": "unknown"
    },
    {
      "Name": "consul-agent",
      "Address": "192.168.130.164",
      "Port": 8500,
      "Status": "unknown"
    },
    {
      "Name": "containerpilot",
      "Address": "165.225.128.237",
      "Port": 9090,
      "Status": "healthy"
    }
  ],
  "Watches": null
}
```

Notice that the `HEALTHY` status on containerpilot is [hardcoded](https://github.com/joyent/containerpilot/blob/master/jobs/jobs.go#L96-L101).

Also, the `got req` logs are reqs from the health check.

```
λ curl http://165.225.129.82:8500/v1/health/service/frontend
```
```json
[
  {
    "Node": {
      "ID": "90ec5966-8bc3-7c40-5b6e-ce2996df0997",
      "Node": "019b5cb7fe1f",
      "Address": "192.168.130.164",
      "Datacenter": "dc1",
      "TaggedAddresses": {
        "lan": "192.168.130.164",
        "wan": "192.168.130.164"
      },
      "Meta": {},
      "CreateIndex": 13,
      "ModifyIndex": 14
    },
    "Service": {
      "ID": "frontend-019b5cb7fe1f",
      "Service": "frontend",
      "Tags": [],
      "Address": "192.168.130.164",
      "Port": 3030,
      "EnableTagOverride": false,
      "CreateIndex": 14,
      "ModifyIndex": 14
    },
    "Checks": [
      {
        "Node": "019b5cb7fe1f",
        "CheckID": "serfHealth",
        "Name": "Serf Health Status",
        "Status": "passing",
        "Notes": "",
        "Output": "Agent alive and reachable",
        "ServiceID": "",
        "ServiceName": "",
        "ServiceTags": [],
        "CreateIndex": 13,
        "ModifyIndex": 13
      },
      {
        "Node": "019b5cb7fe1f",
        "CheckID": "service:frontend-019b5cb7fe1f",
        "Name": "Service 'frontend' check",
        "Status": "passing",
        "Notes": "TTL for frontend set by containerpilot",
        "Output": "ok",
        "ServiceID": "frontend-019b5cb7fe1f",
        "ServiceName": "frontend",
        "ServiceTags": [],
        "CreateIndex": 14,
        "ModifyIndex": 98
      }
    ]
  }
]
```

**Comment by tgross** [comment] 2017-07-26 18:21
Can you turn on debug logging by adding `logging: { level: "DEBUG"}` to the ContainerPilot configuration?

> Also, the got req logs are reqs from the health check.

The health check is just `curl`, so do you mean here that the `got req` logs are your Node.js application's logs? Maybe you can log the status code of that response as well? Because it looks to me that you're getting a failed health check:

> `check.frontend exited with error: check.frontend: exit status 7`

**Comment by ramitos** [comment] 2017-07-26 19:01
> Can you turn on debug logging by adding `logging: { level: "DEBUG"}` to the ContainerPilot configuration?

I thought having a `LOG_LEVEL=DEBUG` was equivalent. 

With `logging: { level: "DEBUG"}`:

```
λ docker logs 5b338419b54f      
2017-07-26T18:55:08.999475827Z control: serving at /var/run/containerpilot.socket
2017-07-26T18:55:09.008014876Z telemetry: serving at 
2017-07-26T18:55:09.133076545Z ==> Starting Consul agent...
2017-07-26T18:55:09.175061527Z ==> Consul agent running!
2017-07-26T18:55:09.843719137Z ==> Newer Consul version available: 0.9.0 (currently running: 0.8.5)
2017-07-26T18:55:09.962050677Z Listening on http://0.0.0.0:3030
2017-07-26T18:55:10.074348091Z 1501095310074 got req
2017-07-26T18:55:11.013798297Z 1501095311013 got req
2017-07-26T18:55:12.012986337Z 1501095312012 got req
2017-07-26T18:55:13.011973385Z 1501095313011 got req
2017-07-26T18:55:14.01541603Z 1501095314015 got req
2017-07-26T18:55:15.013668772Z 1501095315013 got req
2017-07-26T18:55:16.01353769Z 1501095316013 got req
```

> The health check is just curl, so do you mean here that the got req logs are your Node.js application's logs? 

Yes, those are Node.js logs

> Maybe you can log the status code of that response as well?

```
λ docker exec -it 5b338419b54f bash
bash-4.3# curl -v http://localhost:3030/  
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3030 (#0)
> GET / HTTP/1.1
> Host: localhost:3030
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 21
< Date: Wed, 26 Jul 2017 18:57:29 GMT
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
{"hello": "frontend"}
```

> Because it looks to me that you're getting a failed health check

If you notice, that failed health check is before the server starts. Notice the log order:

```
2017-07-25T12:32:20.157763994Z check.frontend exited with error: check.frontend: exit status 7
2017-07-25T12:32:20.323644347Z Listening on http://0.0.0.0:3030
```

**Comment by tgross** [comment] 2017-07-26 20:18
> With logging: { level: "DEBUG"}:

Hm, that's odd. We should see _much_ more verbose logs. Maybe change the log format away from the `default` format too? I know the log format was changed in https://github.com/joyent/containerpilot/releases/tag/3.2.0 so maybe that got broken unintentionally?

> If you notice, that failed health check is before the server starts. Notice the log order:

Ah, yup. And the Consul job status is passing too.

**Comment by tgross** [comment] 2017-07-27 20:11
I just double-checked that we didn't break the log outputs with the new `default` format, so that should be just fine. Can you double-check that you rebuilt your container with the new config file with `logging: { level: "DEBUG"}`? You should see a giant blog at the top of the log where we render-out the ContainerPilot configuration, and not seeing that in your updated logs suggests that got missed.

**Comment by ramitos** [comment] 2017-07-27 20:23
@tgross ah, sorry I might have forgotten to clean the image cache.

```
λ docker logs 15399e748ea6
```
```
2017-07-27T20:21:01.789900304Z loaded config: {"Discovery":{},"LogConfig":{"level":"DEBUG","format":"default","output":"stdout"},"StopTimeout":5,"Jobs":[{"Name":"frontend","Exec":"node /opt/app/index.js","Port":3030,"Interfaces":null,"Tags":null,"ConsulExtras":null,"Health":{"CheckExec":["curl","-o","/dev/null","--fail","-s","http://localhost:3030/"],"CheckTimeout":"","Heartbeat":1,"TTL":5},"ExecTimeout":"","Restarts":"unlimited","StopTimeout":"","When":{"Frequency":"","Source":"","Once":"","Each":"","Timeout":""}},{"Name":"consul-agent","Exec":["/usr/local/bin/consul","agent","-data-dir=/data","-config-dir=/config","-log-level=err","-rejoin","-retry-join","mc.svc.f4b20699-b323-4452-9091-977895896da6.us-east-1.cns.joyent.com","-retry-max","10","-retry-interval","10s"],"Port":8500,"Interfaces":null,"Tags":null,"ConsulExtras":null,"Health":{"CheckExec":"curl -so /dev/null http://localhost:8500","CheckTimeout":"","Heartbeat":10,"TTL":25},"ExecTimeout":"","Restarts":"unlimited","StopTimeout":"","When":{"Frequency":"","Source":"","Once":"","Each":"","Timeout":""}},{"Name":"containerpilot","Exec":null,"Port":9090,"Interfaces":["eth1","eth0","eth0[1]","lo","lo0","inet"],"Tags":["3.2.0"],"ConsulExtras":null,"Health":{"CheckExec":null,"CheckTimeout":"","Heartbeat":5,"TTL":15},"ExecTimeout":"","Restarts":null,"StopTimeout":"","When":{"Frequency":"","Source":"","Once":"","Each":"","Timeout":""}}],"Watches":null,"Telemetry":{"Port":9090,"Interfaces":["eth1","eth0","eth0[1]","lo","lo0","inet"],"Tags":["3.2.0"],"Metrics":null,"MetricConfigs":null,"JobConfig":{"Name":"containerpilot","Exec":null,"Port":9090,"Interfaces":["eth1","eth0","eth0[1]","lo","lo0","inet"],"Tags":["3.2.0"],"ConsulExtras":null,"Health":{"CheckExec":null,"CheckTimeout":"","Heartbeat":5,"TTL":15},"ExecTimeout":"","Restarts":null,"StopTimeout":"","When":{"Frequency":"","Source":"","Once":"","Each":"","Timeout":""}}},"Control":{"SocketPath":"/var/run/containerpilot.socket"}}
2017-07-27T20:21:01.790779928Z event: {Startup global}
2017-07-27T20:21:01.791197263Z control: serving at /var/run/containerpilot.socket
2017-07-27T20:21:01.79165144Z frontend.Run start
2017-07-27T20:21:01.797248633Z consul-agent.Run start
2017-07-27T20:21:01.800332516Z telemetry: serving at 
2017-07-27T20:21:01.851953179Z ==> Starting Consul agent...
2017-07-27T20:21:01.86336623Z ==> Consul agent running!
2017-07-27T20:21:01.866074163Z     2017/07/27 20:21:01 [ERR] agent: failed to sync remote state: No known Consul servers
2017-07-27T20:21:02.402955777Z Listening on http://0.0.0.0:3030
2017-07-27T20:21:02.791448155Z check.frontend.Run start
2017-07-27T20:21:02.812165398Z 1501186862811 got req
2017-07-27T20:21:02.821765652Z check.frontend exited without error
2017-07-27T20:21:03.793369389Z check.frontend.Run start
2017-07-27T20:21:03.810812549Z 1501186863810 got req
2017-07-27T20:21:03.813254944Z check.frontend exited without error
2017-07-27T20:21:04.791484284Z check.frontend.Run start
2017-07-27T20:21:04.802289369Z 1501186864802 got req
2017-07-27T20:21:04.804128403Z check.frontend exited without error
2017-07-27T20:21:05.791536243Z check.frontend.Run start
2017-07-27T20:21:05.809354752Z 1501186865809 got req
2017-07-27T20:21:05.810581353Z check.frontend exited without error
2017-07-27T20:21:06.791571522Z check.frontend.Run start
2017-07-27T20:21:06.803955173Z 1501186866803 got req
2017-07-27T20:21:06.805818205Z check.frontend exited without error
2017-07-27T20:21:07.791528166Z check.frontend.Run start
2017-07-27T20:21:07.809047267Z 1501186867808 got req
2017-07-27T20:21:07.810268556Z check.frontend exited without error
2017-07-27T20:21:08.791598181Z check.frontend.Run start
2017-07-27T20:21:08.802735494Z 1501186868802 got req
2017-07-27T20:21:08.804662649Z check.frontend exited without error
2017-07-27T20:21:09.791557435Z check.frontend.Run start
2017-07-27T20:21:09.803480823Z 1501186869803 got req
2017-07-27T20:21:09.805216962Z check.frontend exited without error
2017-07-27T20:21:10.791584214Z check.frontend.Run start
2017-07-27T20:21:10.81214174Z 1501186870811 got req
2017-07-27T20:21:10.81486758Z check.frontend exited without error
2017-07-27T20:21:11.791575264Z check.frontend.Run start
2017-07-27T20:21:11.797412911Z check.consul-agent.Run start
2017-07-27T20:21:11.809093344Z check.consul-agent exited without error
2017-07-27T20:21:11.810698107Z 1501186871810 got req
2017-07-27T20:21:11.81256767Z check.frontend exited without error
2017-07-27T20:21:11.812811839Z event: {StatusHealthy frontend}
2017-07-27T20:21:12.791557386Z check.frontend.Run start
2017-07-27T20:21:12.802526151Z 1501186872802 got req
2017-07-27T20:21:12.803946796Z check.frontend exited without error
2017-07-27T20:21:13.791812187Z check.frontend.Run start
2017-07-27T20:21:13.808365045Z 1501186873808 got req
2017-07-27T20:21:13.812039356Z check.frontend exited without error
2017-07-27T20:21:14.791771428Z check.frontend.Run start
2017-07-27T20:21:14.803607222Z 1501186874803 got req
2017-07-27T20:21:14.806004798Z check.frontend exited without error
2017-07-27T20:21:14.806328928Z check.frontend.kill
2017-07-27T20:21:15.791772392Z check.frontend.Run start
2017-07-27T20:21:15.803543072Z 1501186875803 got req
2017-07-27T20:21:15.805084889Z check.frontend exited without error
2017-07-27T20:21:16.791821844Z check.frontend.Run start
2017-07-27T20:21:16.812351548Z 1501186876812 got req
2017-07-27T20:21:16.813843916Z check.frontend exited without error
2017-07-27T20:21:17.791612172Z check.frontend.Run start
2017-07-27T20:21:17.803488426Z 1501186877803 got req
2017-07-27T20:21:17.805201187Z check.frontend exited without error
2017-07-27T20:21:18.791609115Z check.frontend.Run start
2017-07-27T20:21:18.811472032Z 1501186878811 got req
2017-07-27T20:21:18.813172053Z check.frontend exited without error
2017-07-27T20:21:19.791611125Z check.frontend.Run start
2017-07-27T20:21:19.805057419Z 1501186879804 got req
2017-07-27T20:21:19.806824181Z check.frontend exited without error
2017-07-27T20:21:20.791850018Z check.frontend.Run start
2017-07-27T20:21:20.812097889Z 1501186880811 got req
2017-07-27T20:21:20.813918938Z check.frontend exited without error
2017-07-27T20:21:21.791669837Z check.frontend.Run start
2017-07-27T20:21:21.797505254Z check.consul-agent.Run start
2017-07-27T20:21:21.812905014Z 1501186881812 got req
2017-07-27T20:21:21.814445759Z check.frontend exited without error
2017-07-27T20:21:21.817956131Z check.consul-agent exited without error
2017-07-27T20:21:22.33193338Z ==> Newer Consul version available: 0.9.0 (currently running: 0.8.5)
2017-07-27T20:21:22.791903078Z check.frontend.Run start
2017-07-27T20:21:22.803431962Z 1501186882803 got req
2017-07-27T20:21:22.805287254Z check.frontend exited without error
2017-07-27T20:21:23.791581837Z check.frontend.Run start
2017-07-27T20:21:23.801855546Z 1501186883801 got req
2017-07-27T20:21:23.803242114Z check.frontend exited without error
2017-07-27T20:21:23.803707129Z event: {StatusHealthy frontend}
2017-07-27T20:21:24.791617896Z check.frontend.Run start
2017-07-27T20:21:24.810211018Z 1501186884809 got req
2017-07-27T20:21:24.811841444Z check.frontend exited without error
2017-07-27T20:21:25.791683848Z check.frontend.Run start
2017-07-27T20:21:25.81221305Z 1501186885811 got req
2017-07-27T20:21:25.8138445Z check.frontend exited without error
2017-07-27T20:21:26.791634299Z check.frontend.Run start
2017-07-27T20:21:26.811667111Z 1501186886811 got req
2017-07-27T20:21:26.815108723Z check.frontend exited without error
2017-07-27T20:21:27.791714445Z check.frontend.Run start
2017-07-27T20:21:27.803903913Z 1501186887803 got req
2017-07-27T20:21:27.805603458Z check.frontend exited without error
2017-07-27T20:21:27.805904141Z check.frontend.kill
2017-07-27T20:21:28.793017571Z check.frontend.Run start
2017-07-27T20:21:28.813756006Z 1501186888813 got req
2017-07-27T20:21:28.817329404Z check.frontend exited without error
2017-07-27T20:21:29.791645465Z check.frontend.Run start
2017-07-27T20:21:29.810039797Z 1501186889809 got req
2017-07-27T20:21:29.811579611Z check.frontend exited without error
2017-07-27T20:21:29.811844777Z check.frontend.kill
```

**Comment by tgross** [comment] 2017-07-27 20:41
One interesting item that jumps out at me in the logs is that we never see `event {StatusHealthy consul-agent}` even though we are seeing `check.consul-agent exited without error`. I do notice that health check is missing the `--fail` option, so let's circle back to that.

But for the frontend check, we do see the `{StatusHealthy frontend}`, which in the code gets fired immediately after we call [`job.setStatus(statusHealthy)`](https://github.com/joyent/containerpilot/blob/818edfb2306c30df7b4f7062386a7d84e4fcee5c/jobs/jobs.go#L253-L254)! So we have pretty good evidence that the job's status is being set to healthy and just isn't being reported correctly. Let me dig into that and see if I can reproduce.

**Comment by ramitos** [comment] 2017-07-27 20:44
Thanks for looking into it. FYI all the code is here: https://gist.github.com/ramitos/9a1bb632d637d9236f21baf9b78bdeff

**Comment by tgross** [comment] 2017-07-27 20:52
I'm about to wrap up for the day here so I'm mostly just leaving this comment as a note as where to pick up in the morning... but given that we're seeing the correct stanzas in the response body _and_ we're almost certainly tracking the status correctly, I suspect the problem is somewhere in [this block](https://github.com/joyent/containerpilot/blob/818edfb2306c30df7b4f7062386a7d84e4fcee5c/telemetry/status.go#L47-L54) where we check the status. So maybe a bug in `GetStatus()` or something in the test for the job names is wrong.

**Comment by tgross** [comment] 2017-07-28 13:13
Ok, picking this up again... I've been able to reproduce this pretty easily with the following config and a `make local build`:

```
{
  consul: "localhost:8500",
  logging: {level: "DEBUG"},
  control: {
    socket: "./containerpilot.sock"
  },
  jobs: [
    {
      name: "app",
      exec: "python -m SimpleHTTPServer",
      port: 8000,
      health: {
        exec: "curl --fail -so /dev/null localhost:8000",
        ttl: 10,
        interval: 5
      }
    }
  ],
  telemetry: {
    port: 9090,
    interfaces: ["lo0"]
  }
}
```

I can see the health checks all passing as expected. But when I add logging to the `ServeHTTP` (`		fmt.Printf("%v status: %v\n", job, status)`), I see that the status field for `containerpilot` and `app` are _switched_! 

```
job: jobs.Job[app] status: healthy
job: jobs.Job[containerpilot] status: unknown
```

But that's not what the status endpoint says:

```json
{
  "Version": "dev-build-not-for-release",
  "Services": [
    {
      "Name": "app",
      "Address": "192.168.1.236",
      "Port": 8000,
      "Status": "unknown"
    },
    {
      "Name": "containerpilot",
      "Address": "127.0.0.1",
      "Port": 9090,
      "Status": "healthy"
    }
  ],
  "Watches": null
}
```

So I suspect we have some probably-obvious-after-the-fact bug in how those are getting mapped. Should be easy enough to track down.

**Comment by ramitos** [comment] 2017-07-28 13:22
Interesting. I thought that `containerpilot` was always healthy because of [this](https://github.com/joyent/containerpilot/blob/master/jobs/jobs.go#L96-L101). But maybe it's not only hardcoded but also miss-mapped.

Thanks for looking into it ;)

**Comment by tgross** [comment] 2017-07-28 13:50
I've opened https://github.com/joyent/containerpilot/pull/450 to fix this. Thanks for your help in debugging @ramitos!

**Comment by tgross** [comment] 2017-07-31 14:17
Fix released in https://github.com/joyent/containerpilot/releases/tag/3.3.1

**Closed by tgross** 2017-07-31 14:17 UTC
Labels: bug, fixed, released, v3.x

**Comment by ramitos** [comment] 2017-07-31 14:32
@tgross thank you very much for looking into this!
