### ISSUE TITLE
Member has conflicting node ID

### ISSUE THREAD

**Issue by lucj** [joyent/containerpilot#322] opened 2017-04-12 13:48 UTC
I have several services running with ContainerPilot, for one of them, I have the following error when it runs, which prevents the local consul agent to register to the consul server.

```
* Failed to join 172.18.0.2: Member '4b7d8eea9a88' has conflicting node ID '7ba08ece-d74e-4b39-b5fb-c9b18a396864' with this agent's ID
```

Seems this can be solved by fixing the node id when running the consul agent: [https://github.com/hashicorp/consul/issues/2877](https://github.com/hashicorp/consul/issues/2877)

How would you recommend to set the node-id in the consul subprocess ?

```
    {
      "command": ["/usr/local/bin/consul", "agent",
                  "-node-id", "something like $(cat /proc/sys/kernel/random/uuid)", ?
                  "-data-dir=/data",
                  "-config-dir=/config",
                  "-rejoin",
                  "-retry-join", "{{ if .CONSUL }}{{ .CONSUL }}{{ else }}consul{{ end }}",
                  "-retry-max", "10",
                  "-retry-interval", "10s"],
      "restarts": "unlimited"
    }
```
Thanks a lot.

**Comment by tgross** [comment] 2017-04-12 14:51
> How would you recommend to set the node-id in the consul subprocess ?

You could do as you're doing there. But it should be pulling the node ID from the hostname, which is going to be unique per container isn't it?

**Comment by lucj** [comment] 2017-04-12 19:34
Thanks Tim. What is the way to have the 'cat' correctly interpreted ?

Also, I do not understand why the node id has conflict for one service in particular, I'll investigate.

**Comment by tgross** [comment] 2017-04-13 12:59
> What is the way to have the 'cat' correctly interpreted ?

The configuration interpolation doesn't run a subshell, so you'll need to inject it in some other way. Either by using the interpolation of an environment variable like `{{ .HOSTNAME }}` or by wrapping the Consul subprocess in a shell script.

> Also, I do not understand why the node id has conflict for one service in particular

Yeah, I've never seen the problem you're experiencing. Is this on Triton?

**Comment by siepkes** [comment] 2017-04-18 08:42
@tgross FIW I have the same issue without container pilot, just plain Consul, in a Triton / SmartOS LX zone (CentOS image). I speculate that there is something in the LX zone implementation which causes the UUID generated as node ID to always be the same for zones on the same CN.

**Comment by tgross** [comment] 2017-04-20 14:05
@siepkes @lucj I'm having trouble figuring out how to replicate this on Triton. I've taken the blueprint in https://github.com/autopilotpattern/consul and run 3 nodes. And then I've added another instance to the cluster like so:

```
docker run -d -p 8500 --env-file ./_env \
  --name consul_consul_4 \  
  --label "triton.cns.services=consul" \
  -e "affinity:container==consul_consul_1" \
  autopilotpattern/consul:latest \
    /usr/local/bin/containerpilot /bin/consul agent -server \
      -bootstrap-expect 3 -config-dir=/etc/consul -ui-dir /ui
```

Note that I'm using an affinity filter here to ensure the 4th node lands on the same CN as the 1st node, and I can confirm this with `for i in {1,2,4}; do triton inst get consul_consul_$i | jq .compute_node; done`. I end up with 4 nodes in Consul just fine, each with their own hostname and node ID.

@siepkes do you have reproduction steps you can share? I must be missing something.

**Comment by siepkes** [comment] 2017-04-20 15:25
@tgross I haven't configured docker in our private Triton instance. So unfortunately I can't run the test you describe. We use a combination of Packer, SaltStack and Terraform to create and deploy our images. I actually only have 1 LX zone image because we needed V8 and that doesn't build on Illumos. I worked around the issue by having systemd generate a persistent unique node-id on first start:

```
ExecStartPre=if [[ ! -f "/var/lib/consul/node-id" ]] ; then echo $(uuidgen -r | awk '{print tolower($0)}') > /var/lib/consul/node-id ; fi 
```

The image I used with Consul in which I get this behavior is CentOS 7 ( `23ee2dbc-c155-11e6-ab6d-bf5689f582fd` ). I don't know if it is relevant but the Consul agent's I used were clients, not servers.

**Comment by tgross** [comment] 2017-04-20 15:43
Ok, well we need to try to create a minimal reproduction here. What can you tell me about the topology of the clients/servers or the sequence of events, @siepkes?

**Comment by lucj** [comment] 2017-04-20 16:11
@tgross @siepkes I got the error when running my compose file against a simple host (using Docker for Mac). I'll try to setup an easy to reproduce env.

**Comment by lucj** [comment] 2017-04-24 21:10
Seems like this occurs with Consul 0.8.0 but it's fine with 0.7.5.
From my understanding 0.8.1 should fix the thing, I'll test this.
@siepkes which version of Consul are you using for Server and Agent ?

**Comment by lucj** [comment] 2017-04-25 08:06
Seems to be fine when local agents (the ones embedded in each service) are running Consul 0.8.1 and server is running 0.7.5.
Attempts to run the server to a version >=0.8.0 raise the error.

**Comment by siepkes** [comment] 2017-04-25 08:27
@lucj I encountered the issue when upgrading to 0.8. Because of the link to the Hashicorp issue I assumed it was clear that this is only an issue with Consul >= 0.8. Sorry, I should have been more verbose about that.

**Comment by lucj** [comment] 2017-04-25 09:07
@siepkes No problem. I though this would be fixed with 0.8.1 but it's not.
Good thing the agent can use 0.8.1 though.

**Comment by lucj** [comment] 2017-04-25 09:14
My bad, everything needs to be in version <0.8.0

**Comment by tgross** [comment] 2017-04-25 12:54
> From my understanding 0.8.1 should fix the thing, I'll test this.

Good to know. Can you provide a link to the Hashicorp Consul issue for where that might have been discussed and/or fixed?

**Comment by lucj** [comment] 2017-04-25 12:57
In fact I did not manage to have it working with 0.8.1.
From the change log https://github.com/hashicorp/consul/blob/master/CHANGELOG.md
```
agent: Node IDs derived from host information are now hashed to prevent things like common server hardware from generating IDs with a common prefix across nodes. [GH-2884]
```

**Comment by tgross** [comment] 2017-04-25 15:58
Ok, I did a little digging and I think we can work around this. Try passing `-node-id={{ .HOSTNAME }}` as part of your ContainerPilot configuration for the Consul agent.

**Comment by EugenMayer** [comment] 2017-05-01 16:27
You can go back with https://www.consul.io/docs/agent/options.html#_disable_host_node_id .. because -node-id={{ .HOSTNAME }} will not work due to  `Error starting agent: Failed to setup node ID: uuid string is wrong length`

**Comment by tgross** [comment] 2017-05-03 14:31
@EugenMayer that seems like the way to go then. We're also going to look into what might be generating the conflicting node IDs and trying to suss out whether this is a Triton issue (which seems unlikely as it's happening on Docker for Mac) or a Consul issue.

**Comment by EugenMayer** [comment] 2017-05-03 14:44
Probably kind of related topic: https://groups.google.com/forum/#!topic/consul-tool/9lm0HbyQVd4

**Comment by tgross** [comment] 2017-05-03 18:33
@lucj I'm still unable to reproduce this, so it might help if we could get some more information from you about the conditions where you're seeing this problem.

- what version(s) of Consul, ContainerPilot, and Docker works? which versions don't work?
- is the data directory for Consul being reused? i.e. are you using `-v` arguments to mount it as a volume?
- are you seeing the problem only on Docker for Mac, Docker Machine, or Triton. Or more than one?
- if you're seeing the problem on Triton can you get the PI (if on-prem) or provide the CN (`triton inst get mycontainer | json compute_node` will get this, or you can email me the UUIDs of the containers and I can dig this up at our end).

**Comment by sean-** [comment] 2017-05-03 18:36
Those are unrelated.  The background on those issues is that some providers use a timestamp-prefixed UUID, which makes the first 10 characters effectively useless.  Hashing the full UUID, however, gives a sense of randomness to the first 10 characters.

But, Consul should, and properly detects node-id collisions.  If consul is being seeded with a duplicate node-id, then this could happen.  Consul is pointing out a discrepancy in the environment.  Where it is, however, is what we're trying to figure out.  CC @tgross

**Comment by lucj** [comment] 2017-05-03 19:49
@tgross, here is a compose version that makes this error occur.

```
version: '2'
services:

  consul:
    image: consul:0.8.0
    command: agent -server -client=0.0.0.0 -bootstrap -ui
    dns:
      - 127.0.0.1
    ports:
      - "8500:8500"
    restart: always

  db:
    image: autopilotpattern/mongodb
    restart: always

  mq:
    image: autopilotpattern/rabbitmq
    build: ../../../development/rabbitmq
    restart: always

  profile:
    image: traxxs/profile:develop
    build: ../../../development/profile
    command: ["containerpilot", "npm", "start"]
    restart: always
```

The service mq is based on https://github.com/lucj/autopilotpattern-rabbitmq, using Consul 0.8.0.
The service profile is a part of our application, that is also using Consul 0.8.0 and that depends on mq and db services.

Below is the part of the logs where profile is starting (moving out of the preStart once the db and mq are up and running). You can see the Node ID error in it.

```
profile_1  | db is healthly, moving on...
profile_1  | mq is healthly, moving on...
profile_1  | 2017/05/03 19:37:20 ==> Starting Consul agent...
profile_1  | 2017/05/03 19:37:20 ==> Consul agent running!
profile_1  | 2017/05/03 19:37:20            Version: 'v0.8.0'
profile_1  | 2017/05/03 19:37:20            Node ID: '7ba08ece-d74e-4b39-b5fb-c9b18a396864'
profile_1  | 2017/05/03 19:37:20          Node name: 'ba77cfe3461f'
profile_1  | 2017/05/03 19:37:20         Datacenter: 'dc1'
profile_1  | 2017/05/03 19:37:20             Server: false (bootstrap: false)
profile_1  | 2017/05/03 19:37:20        Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600)
profile_1  | 2017/05/03 19:37:20       Cluster Addr: 172.18.0.2 (LAN: 8301, WAN: 8302)
profile_1  | 2017/05/03 19:37:20     Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
profile_1  | 2017/05/03 19:37:20              Atlas: <disabled>
profile_1  | 2017/05/03 19:37:20
profile_1  | 2017/05/03 19:37:20 ==> Log data will now stream in as it occurs:
profile_1  | 2017/05/03 19:37:20
profile_1  | 2017/05/03 19:37:20     2017/05/03 19:37:20 [INFO] serf: EventMemberJoin: ba77cfe3461f 172.18.0.2
profile_1  | 2017/05/03 19:37:20     2017/05/03 19:37:20 [WARN] manager: No servers available
profile_1  | 2017/05/03 19:37:20     2017/05/03 19:37:20 [INFO] agent: Joining cluster...
profile_1  | 2017/05/03 19:37:20     2017/05/03 19:37:20 [ERR] agent: failed to sync remote state: No known Consul servers
profile_1  | 2017/05/03 19:37:20     2017/05/03 19:37:20 [INFO] agent: (LAN) joining: [consul]
consul_1   |     2017/05/03 19:37:20 [INFO] serf: EventMemberJoin: ba77cfe3461f 172.18.0.2
consul_1   |     2017/05/03 19:37:20 [INFO] consul: member 'ba77cfe3461f' joined, marking health alive
profile_1  | 2017/05/03 19:37:20     2017/05/03 19:37:20 [INFO] agent: (LAN) joined: 0 Err: 1 error(s) occurred:
profile_1  | 2017/05/03 19:37:20
profile_1  | 2017/05/03 19:37:20 * Failed to join 172.18.0.5: Member '5a27f0cf077b' has conflicting node ID '7ba08ece-d74e-4b39-b5fb-c9b18a396864' with this agent's ID
profile_1  | 2017/05/03 19:37:20     2017/05/03 19:37:20 [WARN] agent: Join failed: <nil>, retrying in 10s
consul_1   |     2017/05/03 19:37:20 [INFO] consul.fsm: EnsureRegistration failed: failed inserting node: node ID "7ba08ece-d74e-4b39-b5fb-c9b18a396864" for node "ba77cfe3461f" aliases existing node "5a27f0cf077b"
mq_1       | 2017/05/03 19:37:20     2017/05/03 19:37:20 [WARN] memberlist: ignoring alive message for 'ba77cfe3461f': Member 'ba77cfe3461f' has conflicting node ID '7ba08ece-d74e-4b39-b5fb-c9b18a396864' with this agent's ID
mq_1       | 2017/05/03 19:37:21     2017/05/03 19:37:21 [WARN] memberlist: ignoring alive message for 'ba77cfe3461f': Member 'ba77cfe3461f' has conflicting node ID '7ba08ece-d74e-4b39-b5fb-c9b18a396864' with this agent's ID
profile_1  |
profile_1  | > profile@0.0.1 start /app
profile_1  | > node index.js
profile_1  |
profile_1  | --- www server listering on port [80] --
```


To reply to your questions:
- ContainerPilot is 2.7.2 in both mq and profile.
- I do not mount volumes
- I only tested this on Docker for Mac

If all the services are using Consul 0.7.5 instead of 0.8.0 the problem does not occur.

**Comment by mterron** [comment] 2017-05-04 01:53
You can pass "-disable-host-node-id=true" to the consul (>0.8.1) run command to make it generate a random node-id. It can't be reproduced on Triton, as it is a Consul-Docker issue. 

Cheers

**Comment by tgross** [comment] 2017-05-17 18:08
Closing this, as it's a Consul issue.

**Closed by tgross** 2017-05-17 18:08 UTC
Labels: usage

**Comment by EugenMayer** [comment] 2017-05-18 08:37
@tgross are there any issues you refer too? i am very interested

**Comment by tgross** [comment] 2017-05-18 12:31
Just the [Consul mailing list issue](https://groups.google.com/forum/#!topic/consul-tool/9lm0HbyQVd4) that you opened. Use [`-disable-host-node-id`](https://www.consul.io/docs/agent/options.html#_disable_host_node_id) as was advised there.
