### ISSUE TITLE
Annotate logs by generating process

### ISSUE THREAD

**Issue by jhmartin** [joyent/containerpilot#393] opened 2017-06-09 20:33 UTC
Coprocesses and tasks have names. When those processes emit STDOUT logs, include that name tag in some sort of parseable fashion so that log parsers can differentiate between each process. Include a tag on the 'main' process as well.

**Comment by tgross** [comment] 2017-06-09 20:50
In v2 we didn't add log structure because we had a "main" application which was assumed to take care of its own log structure. The `coprocess` and `task` hooks came later and probably should have had log structure but didn't because we reused most of the mechanisms we were using to run the "main" application. It looks like you're proposing adding this as a feature but we're not adding any new features to v2 of ContainerPilot.

However in v3 of ContainerPilot (the master branch and [release candidate](https://github.com/joyent/containerpilot/releases/tag/3.0.0-RC1)) no longer has a concept of a "main" application and we do wrap all the log lines for each `job` in the log structure. I was pretty sure we have the job names in the fields already but I'll double-check. In the meantime I'll mark this as a `3.x` proposal.

**Comment by tgross** [comment] 2017-07-03 20:16
@jhmartin I dug into this area while looking at #423 and discovered a few things (ref https://github.com/joyent/containerpilot/issues/423#issuecomment-312725831):

- we're definitely supposed to be setting up the commands so that they log their names
- we accidentally broke the logger that was supposed to pick up those names in v3
- we had a regression in v2 on the same item in 2.7.1.

I've got a fix in the works and I'll have it up for review sometime Weds morning.

**Comment by tgross** [comment] 2017-07-03 20:27
PR open for v3 https://github.com/joyent/containerpilot/pull/424

**Comment by tgross** [comment] 2017-07-05 14:23
I've merged #424 and #425 and I'll release that fix in ContainerPilot 2.7.6 and ContainerPilot 3.1.3. I want to make sure we've done what we can about #423 first, but I won't hold the patch release up for long if that proves to be a lengthy process.

**Comment by tgross** [comment] 2017-07-05 18:04
Released in https://github.com/joyent/containerpilot/releases/tag/3.1.3 and https://github.com/joyent/containerpilot/releases/tag/2.7.6

**Closed by tgross** 2017-07-05 18:04 UTC
Labels: awaiting release, bug, v2, v3.x

**Comment by mterron** [comment] 2018-01-15 00:12
Does not log job names on 3.6.2 @tgross 
Example log there should be a "redis" after the timestamp and before the 19:M:
```
2018-01-15T00:03:49.607445593Z 19:M 15 Jan 00:03:49.607 * 10000 changes in 60 seconds. Saving...
2018-01-15T00:03:49.609117243Z 19:M 15 Jan 00:03:49.608 * Background saving started by pid 995
2018-01-15T00:03:49.63182348Z 995:C 15 Jan 00:03:49.631 * DB saved on disk
2018-01-15T00:03:49.709621459Z 19:M 15 Jan 00:03:49.709 * Background saving terminated with success
2018-01-15T00:04:50.078460973Z 19:M 15 Jan 00:04:50.078 * 10000 changes in 60 seconds. Saving...
2018-01-15T00:04:50.081086412Z 19:M 15 Jan 00:04:50.079 * Background saving started by pid 1503
2018-01-15T00:04:50.113329473Z 1503:C 15 Jan 00:04:50.113 * DB saved on disk
2018-01-15T00:04:50.179568328Z 19:M 15 Jan 00:04:50.179 * Background saving terminated with success
2018-01-15T00:05:51.081603133Z 19:M 15 Jan 00:05:51.081 * 10000 changes in 60 seconds. Saving...
2018-01-15T00:05:51.084439175Z 19:M 15 Jan 00:05:51.084 * Background saving started by pid 2011
2018-01-15T00:05:51.107568502Z 2011:C 15 Jan 00:05:51.107 * DB saved on disk
2018-01-15T00:05:51.186578762Z 19:M 15 Jan 00:05:51.186 * Background saving terminated with success
2018-01-15T00:06:52.064484068Z 19:M 15 Jan 00:06:52.064 * 10000 changes in 60 seconds. Saving...
2018-01-15T00:06:52.068001052Z 19:M 15 Jan 00:06:52.067 * Background saving started by pid 2519
2018-01-15T00:06:52.091804705Z 2519:C 15 Jan 00:06:52.091 * DB saved on disk
2018-01-15T00:06:52.169475417Z 19:M 15 Jan 00:06:52.169 * Background saving terminated with success
2018-01-15T00:10:17.052457659Z 19:M 15 Jan 00:10:17.052 * 10000 changes in 60 seconds. Saving...
2018-01-15T00:10:17.058806185Z 19:M 15 Jan 00:10:17.054 * Background saving started by pid 4335
2018-01-15T00:10:17.09716568Z 4335:C 15 Jan 00:10:17.096 * DB saved on disk
2018-01-15T00:10:17.159084084Z 19:M 15 Jan 00:10:17.158 * Background saving terminated with success
`

**Comment by cheapRoc** [comment] 2018-01-25 22:08
@mterron This sounds like a bug. Can you file an official issue along with configurations you're using? I'd like to fix this as well.

Has it been removed for all log formats?
