### ISSUE TITLE
Reload issue with stopped events

### ISSUE THREAD

**Issue by aleerizw** [joyent/containerpilot#465] opened 2017-08-08 11:50 UTC
Hi,
We have noticed a strange behavior when reloading containerpilot config. If the config contains jobs with stopped (or stopping) events the reload doesn't work. Reloading works fine if there's no job with a stopped / stopping condition.

Example config:
```
jobs: [
    {
      name: "prestart",
      exec: "/bin/prestart.sh",
      when: {
        source: "global",
        each: "startup"
      }
    },
    {
      name: "app",
      exec: "tail -f /dev/null",
      when: {
        source: "prestart",
        once: "exitSuccess"
      }
    },
    {
      name: "preStop",
      exec: "/bin/true",
      when: {
        source: "app",
        each: "stopping"
      },
    }
  ]
```

Following is the output log:
```
2017-08-08T11:12:39.363033143Z * Reloading containerpilot
2017-08-08T11:12:39.36726755Z control: reloading app via control plane
2017-08-08T11:12:39.367357137Z event: {Shutdown global}
2017-08-08T11:12:39.367397102Z control: reloaded app via control plane
2017-08-08T11:12:39.367491421Z telemetry: stopping server
2017-08-08T11:12:39.367525677Z telemetry: completed graceful shutdown of server
2017-08-08T11:12:39.367571822Z telemetry: stopped serving at 
2017-08-08T11:12:39.367621615Z control: stopping control server
2017-08-08T11:12:39.367692358Z control: completed graceful shutdown of control server
2017-08-08T11:12:39.367747844Z control: stopped serving at /var/run/containerpilot.socket
2017-08-08T11:12:39.367772755Z event: {Stopping prestart}
2017-08-08T11:12:39.367795739Z event: {Stopped prestart}
2017-08-08T11:12:39.36783026Z prestart.term
2017-08-08T11:12:39.367846018Z terminating command 'prestart' at pid: 16
2017-08-08T11:12:39.367888389Z event: {Stopping app}
2017-08-08T11:12:39.367921949Z preStop.Run start
2017-08-08T11:12:39.368473267Z event: {Stopping containerpilot}
2017-08-08T11:12:39.368524548Z deregistering: containerpilot-8be895b0be41
2017-08-08T11:12:39.371943154Z prestart exited with error: signal: terminated
2017-08-08T11:12:39.371974647Z event: {ExitFailed prestart}
2017-08-08T11:12:39.371997806Z event: {Error prestart: signal: terminated}
2017-08-08T11:12:39.372048699Z prestart.Run end
2017-08-08T11:12:39.372118251Z preStop exited without error
2017-08-08T11:12:39.372131995Z event: {ExitSuccess preStop}
2017-08-08T11:12:39.372154594Z preStop.Run end
2017-08-08T11:12:39.372196254Z preStop.term
2017-08-08T11:12:39.37220646Z terminating command 'preStop' at pid: 26
2017-08-08T11:12:39.39334925Z deregistering failed: Put http://localhost:8500/v1/agent/service/deregister/containerpilot-8be895b0be41: dial tcp 127.0.0.1:8500: getsockopt: connection refused
2017-08-08T11:12:39.393388952Z event: {Stopped containerpilot}
```

Please see the following gist for a bare bone recreation of the issue:
https://gist.github.com/aleerizw/f61ad1408700b57aa4c97161ea88110a

We are using containerpilot version 3.3.2.

**Comment by tgross** [comment] 2017-08-08 12:17
Thanks for the report @aleerizw. I'll look into this first thing today.

**Comment by tgross** [comment] 2017-08-08 13:11
I've been able to replicate the behavior with your repro steps, so thanks for providing that. Another data point is that when I run this container with `docker run -it`, that sending SIGINT (via Ctrl-C) doesn't work either. The signal is received and processed, then the `{Shutdown global}` event shows up twice in the logs (apparently two distinct events) but the container doesn't exit. That gives me a place to start looking.

**Comment by tgross** [comment] 2017-08-08 13:46
It looks like this bug was probably introduced in https://github.com/joyent/containerpilot/releases/tag/3.1.2, which included #421 in an attempt to fix #420. Because reloading involves setting a reload flag and then publishing the global shutdown event, the jobs that are waiting for stopping/stopped would fail to execute if they didn't ignore the shutdown. The jobs do need to execute during reload for correctness, so that behavior is correct. But I instrumented the event bus registration/deregistration functions, and it looks like the `preStop` isn't being deregistered, which prevents the event bus from shutting down and allowing reload to proceed. So I just need to figure out that next.

**Comment by tgross** [comment] 2017-08-08 14:00
I've narrowed down the behavior a bit more: the bug is specific to case where we've configured with `each: "stopping"` or `each: "stopped"`, but not `once: "stopping"` or `once: "stopped"`.

- the `preStop` job receives the global shutdown event
- the `preStop` job runs its exec
- the exec publishes the `{ExitSuccess preStop}` event
- the `preStop` job receive this event, and calls `processEvent`
- `preStop`.`processEvent` sees the job has "unlimited" as the value of its `startsRemain` because this is an `each` job, and so `processEvent` returns false (meaning "continue")
- the `preStop` job continues to wait for more events.

I think what we'll need to do here is to have the global shutdown event update the `startsRemain` field for instances with unlimited starts (i.e. those with a `when->each` configuration). I'm going to see if I can make that work next.

**Comment by tgross** [comment] 2017-08-08 14:15
I've opened https://github.com/joyent/containerpilot/pull/466 with the fix.

**Comment by aleerizw** [comment] 2017-08-08 14:18
Thanks for the quick fix!

**Comment by tgross** [comment] 2017-08-08 16:55
Released in https://github.com/joyent/containerpilot/releases/tag/3.3.3

**Comment by aleerizw** [comment] 2017-08-09 09:23
Hi,

We are still experiencing the issue with the new 3.3.3 release but is intermittent now. 
I have updated the gist with a test that runs creates the container and tries reloading the config multiple times and it fails consistently over multiple tries.

https://gist.github.com/aleerizw/f61ad1408700b57aa4c97161ea88110a

**Comment by tgross** [comment] 2017-08-09 12:27
That's unfortunate. Lemme dig into that.

**Comment by tgross** [comment] 2017-08-09 13:03
Ok, I've been able to reproduce what you're seeing. Two observations I've made so far by tinkering with the configuration file:
- If I remove the `telemetry` block in the configuration I can't reproduce. But if I replace the `telemetry` block with another job, the problem returns. When the telemetry block is present it registers to the same event bus as the jobs, so tearing that down is in the code path for a reload. This and the intermittent nature of the problem suggests there's a race condition in the teardown of jobs.
- If I swap out `each` for `once` in the configuration, as I suspected was the problem previously, the problem still occurs.

I've modified your test runner slightly in order to speed up iterations as I try to fix this:

```bash
#!/bin/bash
set -e
docker rm -f reloader || true

for i in $(seq 1 30);
do
    docker run -d \
           --name reloader \
           -v "$(pwd)/build/containerpilot:/bin/containerpilot" \
           -v "$(pwd)/local.json5:/etc/containerpilot.json5" \
           -v "$(pwd)/prestart.sh:/bin/prestart.sh" \
           reloader > /dev/null
    sleep 2
    count=$(docker logs reloader | grep -c "loaded config:")
    if [ "$count" -ne 2 ]; then
        echo
        echo "---------------------------"
        docker logs reloader
        echo "---------------------------"
        echo "**  FAILED AFTER $i RUNS **"
        exit 1
    else
        echo -n "."
    fi
    docker rm -f reloader  > /dev/null
done
echo
echo "** PASS **"

```

Resulting logs:

```
$ ./runtest.sh
Error response from daemon: No such container: reloader
.....
---------------------------
2017-08-09T12:55:40.340060745Z loaded config: ... (elided)
2017-08-09T12:55:40.340358188Z control: initialized router for control server
2017-08-09T12:55:40.340891448Z event: {Startup global}
2017-08-09T12:55:40.341052654Z control: serving at /var/run/containerpilot.socket
2017-08-09T12:55:40.341662022Z prestart.Run start
2017-08-09T12:55:40.363097281Z telemetry: serving at
2017-08-09T12:55:40.365157407Z * Reloading containerpilot
2017-08-09T12:55:40.37448121Z control: reloading app via control plane
2017-08-09T12:55:40.374646112Z event: {Shutdown global}
2017-08-09T12:55:40.374692256Z control: reloaded app via control plane
2017-08-09T12:55:40.375219024Z telemetry: stopping server
2017-08-09T12:55:40.375326395Z telemetry: completed graceful shutdown of server
2017-08-09T12:55:40.375393714Z telemetry: stopped serving at
2017-08-09T12:55:40.375452044Z control: stopping control server
2017-08-09T12:55:40.375573498Z control: stopped serving at /var/run/containerpilot.socket
2017-08-09T12:55:40.375609954Z event: {Stopping prestart}
2017-08-09T12:55:40.375693454Z event: {Stopped prestart}
2017-08-09T12:55:40.375752183Z prestart.term
2017-08-09T12:55:40.375798827Z terminating command 'prestart' at pid: 16
2017-08-09T12:55:40.375935164Z event: {Stopping app}
2017-08-09T12:55:40.376065707Z preStop.Run start
2017-08-09T12:55:40.376752782Z event: {Stopping containerpilot}
2017-08-09T12:55:40.376785642Z deregistering: containerpilot-bc3118da4d6f
2017-08-09T12:55:40.378221418Z prestart exited with error: signal: terminated
2017-08-09T12:55:40.378256276Z event: {ExitFailed prestart}
2017-08-09T12:55:40.378324994Z event: {Error prestart: signal: terminated}
2017-08-09T12:55:40.37838632Z prestart.Run end
2017-08-09T12:55:40.378478809Z preStop exited without error
2017-08-09T12:55:40.378515365Z event: {ExitSuccess preStop}
2017-08-09T12:55:40.378573995Z preStop.Run end
2017-08-09T12:55:40.378630726Z preStop.term
2017-08-09T12:55:40.378657295Z terminating command 'preStop' at pid: 27
2017-08-09T12:55:40.378673575Z job exited but restart not permitted: preStop
2017-08-09T12:55:40.378713827Z event: {Stopping preStop}
2017-08-09T12:55:40.378747286Z event: {Stopped preStop}
2017-08-09T12:55:40.378907494Z event: {Stopped app}
2017-08-09T12:55:40.379615044Z deregistering failed: Put http://localhost:8500/v1/agent/service/deregister/containerpilot-bc3118da4d6f: dial tcp 127.0.0.1:8500: getsockopt: connection refused
2017-08-09T12:55:40.379655196Z event: {Stopped containerpilot}
---------------------------
**  FAILED AFTER 6 RUNS **
```

**Comment by tgross** [comment] 2017-08-09 14:39
Ok, this problem looks to be unrelated to the original problem in this issue. There's a race condition in the code that shuts down the control socket server. It really doesn't have anything to do with stopped/stopping jobs, but it's a very tight race and those jobs tend to slow down the shutdown enough that the race condition is more likely to appear.

I can't precisely instrument the relevant section of code because unfortunately that causes the race to always work out without a deadlock, but here's what appears to be order of events in the case of a deadlock:

- shutdown event is published
- control server receives the shutdown event on its [`Rx`](https://github.com/joyent/containerpilot/blob/fa27bdab528cf4c40f0aef8c0ef9fbfa564aad01/control/control.go#L62) channel.
- job1 also receives the shutdown event on its Rx channel.
- control server goroutine that's listening for events returns and fires its [`defer srv.Stop()`](https://github.com/joyent/containerpilot/blob/fa27bdab528cf4c40f0aef8c0ef9fbfa564aad01/control/control.go#L60)
- control server hits [`Shutdown`](https://github.com/joyent/containerpilot/blob/fa27bdab528cf4c40f0aef8c0ef9fbfa564aad01/control/control.go#L133). This blocks and lets other goroutines run, so we don't hit the next line in this code path until the end of this test.
- [`srv.Serve`](https://github.com/joyent/containerpilot/blob/fa27bdab528cf4c40f0aef8c0ef9fbfa564aad01/control/control.go#L96) returns.
- job1 hits [`Unsubscribe`](https://github.com/joyent/containerpilot/blob/fa27bdab528cf4c40f0aef8c0ef9fbfa564aad01/jobs/jobs.go#L356), leaving only the control server as last remaining event listener
- job1 hits [`Publish`](https://github.com/joyent/containerpilot/blob/fa27bdab528cf4c40f0aef8c0ef9fbfa564aad01/events/bus.go#L110) for its `stopped` event, gets the lock, but the control server goroutine has already returned, which means there's no one listening for the published event and we block forever. This means we never release the lock.
- control server's `Stop` method hits [`Unsubscribe`](https://github.com/joyent/containerpilot/blob/fa27bdab528cf4c40f0aef8c0ef9fbfa564aad01/control/control.go#L138)
- [`Bus.Unregister(controlServer)`](https://github.com/joyent/containerpilot/blob/fa27bdab528cf4c40f0aef8c0ef9fbfa564aad01/events/bus.go#L98) tries to obtain bus lock but blocks because job1 hasn't given it up yet. And this is our deadlock.

Right now I'm not convinced this race doesn't already exist in the regular jobs, and that we're only seeing it in the control server because the gap between stopping the listening loop and unregistration is much longer in the control server than it is in the jobs. So that's what I'm looking at next.

**Comment by tgross** [comment] 2017-08-09 14:44
There's something not quite right about the above, actually -- this channel is buffered, which means it shouldn't be blocking even if there are no receivers. I think it's just full!

**Comment by tgross** [comment] 2017-08-09 21:04
Just pushed this release up with the fix https://github.com/joyent/containerpilot/releases/tag/3.3.4

I'm going to circle back tomorrow to this to reduce the code complexity, but this should fix the immediate bug.

**Closed** 2017-08-10 12:36 UTC
Labels: bug, released, v3.x
