### ISSUE TITLE
with docker bridged mode I can't set the consul service instance address properly

### ISSUE THREAD

**Issue by wleese** [joyent/containerpilot#102] opened 2016-03-04 11:41 UTC
When running in bridge mode none of the interfaces available to containerbuddy contains the actual IP that needs to be advertised to consul.

I'd actually expect that leaving out the interfaces configuration would magically use the consul agent IP. But whatever the case it seems useful to be able to explicitly set the IP through a variable for docker bridged mode users.

**Comment by tgross** [comment] 2016-03-04 13:22
> When running in bridge mode none of the interfaces available to containerbuddy contains the actual IP that needs to be advertised to consul.

Correct, and this is by design.

You'll need a sane networking environment without NAT or port mapping -- that is, one where the IP inside the container is the same IP that one uses to reach the container. This sort of set up is available via Docker Swarm with overlay networking, with Mantl, or with Triton. This is what allows you to avoid having on-host proxies, load balancers, port mapping, NAT, etc. between intercommunicating containers, and what allows you to avoid use of an external scheduling tool that also gets its fingers into your networking environment (ex. Kubernetes, Rancher).

In a lot of the supporting written material and talks we've done around Containerbuddy we've talked about this a lot (see the [Examples](https://github.com/joyent/containerbuddy#examples) section at the bottom of the README), but I'll admit it's definitely a documentation bug not to explicitly call this out.

**Comment by wleese** [comment] 2016-03-04 14:01
> You'll need a sane networking environment

I agree, we do need that. However at the moment that's not what we have. We'll be moving to all containers having their own IP in the future.

Now that said, without waiting for the above, we'd like to test and use containerbuddy right from the start. Is there any reason this cannot be implemented?

**Comment by tgross** [comment] 2016-03-04 14:42
> Is there any reason this cannot be implemented?

It would be *technically* trivial to support "announce a particular statically configured IP address" in Containerbuddy, but it would be at cross purposes with the intended purpose.

Containerbuddy is designed to provide the orchestration required for active service discovery. If you can inject the IP address into the container at start time, then you already know what the IP is from some external source of truth (maybe your scheduler?). In which case, Containerbuddy isn't providing you with anything -- you could use this same external source to inject the data directly into the discovery service in the first place.

**Comment by wleese** [comment] 2016-03-04 14:58
> If you can inject the IP address into the container at start time, then you already know what the IP is from some external source of truth (maybe your scheduler?)

That would be Terraform -> Marathon -> Mesos -> Docker

> Containerbuddy isn't providing you with anything -- you could use this same external source to inject the data directly into the discovery service

That's fair, we could use terraform for that. But we're in a phase where we will move to proper networking for our containers. We're just not there yet. By not having this feature we'd be unable to evaluate containerbuddy in the mean time.

Of course, we could continue to use the silly patch in the above PR and then switch over to clean containerbuddy in the future. But I'm sure other people will be run into this caveat every once in awhile.

**Comment by tgross** [comment] 2016-03-04 16:15
Ok, this isn’t something we have use for, and it sounds like it only has temporary use for you as well, but I definitely can see your reasoning to want to go down this path.

However, we don’t have an environment handy in which we can test this, so we’re looking to you to take the lead on developing the patch and tests, and documenting the workflow (preferably with example code/config for that as well). We’ll help guide the pull request to something that we might be able to mainline later, but it would be best to more fully develop a feature as divergent as this in your branch.

If that works for you, let’s keep https://github.com/joyent/containerbuddy/pull/103 open while you build and test? I've got some comments to add in the PR which I'll do next.

**Comment by tgross** [comment] 2016-03-08 20:58
https://github.com/joyent/containerbuddy/pull/103 has been merged and we'll release this in 1.2.0

**Comment by misterbisson** [comment] 2016-03-09 16:07
@wleese would you mind sharing more information about how you'll use this feature? I know you said "Terraform -> Marathon -> Mesos -> Docker," but that leaves a lot unsaid. Would you be willing to write it up?

**Comment by wleese** [comment] 2016-03-09 19:45
Sure.

Due to legacy infrastructure we're forced to move slowly and start off our mesos cluster using docker containers with bridge networking - container IPs aren't visible outside of the mesos host. No amount of traversing network interfaces within the container will find an IP that can be advertised to consul as that containers address.

Now we can specify the IP advertised to consul using containerbuddy, we can tell all our mesos slaves to expose a variable that contains the IP of that mesos slave. Which we use in containerbuddys app.json. If the container dies and moves onto a different slave, the variable will resolve to the new mesos slave and update consul accordingly.

Looking back I shouldn't have mentioned terraform :)

**Comment by misterbisson** [comment] 2016-03-09 20:19
@wleese can you please be more specific about what environment variable you're getting the host IP address from and other details? 

Are you using Marathon? Can you share an example application definition? Basically: how would somebody else use this in the way you intend to?

**Comment by wleese** [comment] 2016-03-10 11:54
I created a new patch that would resolve the HOST variable, which is the ip on the mesos slave.

I presumed that patch wouldn't be necessary. It seemed at the time that we'd be able to insert the IP into the containers by configuring Mesos/Marathon to do so. Sadly this seems impossible:

https://github.com/mesosphere/marathon/issues/1328
https://github.com/mesosphere/marathon/issues/1828
https://github.com/mesosphere/marathon/issues/2679
Non-solution: https://github.com/mesosphere/marathon/issues/641

Docs: https://mesosphere.github.io/marathon/docs/task-environment-vars.html

This is what we currently do:

`{
  "consul": "{{.HOST}}:8500",
  "stopTimeout": -1,
  "services": [
    {
      "name": "mytestapp",
      "port": {{.PORT}},
      "ipaddress": "{{.HOST}}",
      "health": [
        "socat",
        "-",
        "TCP4:localhost:8080"
      ],
      "poll": 10,
      "ttl": 30
    }
  ]
}`

Consul agent listens on the mesos slave at $HOST:8500.

Terraform talks to marathon:

`
        {
            "acceptedResourceRoles": null,
            "args": null,
            "backoffFactor": 1.15,
            "backoffSeconds": 1,
            "cmd": null,
            "constraints": [
                [
                    "hostname",
                    "CLUSTER",
                    "tst"
                ]
            ],
            "container": {
                "docker": {
                    "forcePullImage": true,
                    "image": "r/infra/dcb:latest",
                    "network": "BRIDGE",
                    "parameters": [],
                    "portMappings": [
                        {
                            "containerPort": 6379,
                            "hostPort": 0,
                            "protocol": "tcp",
                            "servicePort": 10004
                        }
                    ],
                    "privileged": false
                },
                "type": "DOCKER",
                "volumes": []
            },
            "cpus": 0.01,
            "dependencies": [],
            "deployments": [],
            "disk": 0.0,
            "env": {
                "APPLICATION": "logredis2",
                "CONSUL_HTTP_TOKEN": "xxxxx",
                "ENVIRONMENT": "tst",
                "KIND": "tst",
                "MEMORY": "512.0",
                "NODE_NUMBER": "0",
            },
            "executor": "",
            "fetch": [],
            "healthChecks": [],
            "id": "/tst-logredis2/0",
            "instances": 1,
            "ipAddress": null,
            "labels": {},
            "maxLaunchDelaySeconds": 3600,
            "mem": 512,
            "ports": [
                10004
            ],
            "requirePorts": false,
            "storeUrls": [],
            "tasksHealthy": 0,
            "tasksRunning": 1,
            "tasksStaged": 0,
            "tasksUnhealthy": 0,
            "upgradeStrategy": {
                "maximumOverCapacity": 1,
                "minimumHealthCapacity": 0.5
            },
            "uris": [],
            "user": null,
            "version": "2016-03-10T11:45:15.808Z",
            "versionInfo": {
                "lastConfigChangeAt": "2016-03-10T11:45:15.808Z",
                "lastScalingAt": "2016-03-10T11:45:15.808Z"
            }
        }
`

This is the extra patch I'm using:
`diff --git a/containerbuddy/config.go b/containerbuddy/config.go
index 6661f92..cac364c 100644
--- a/containerbuddy/config.go
+++ b/containerbuddy/config.go
@@ -318,8 +318,12 @@ func initializeConfig(config *Config) (*Config, error) {
 			}
 		} else {
 			if ok := net.ParseIP(service.IpAddress); ok == nil {
-				return nil, fmt.Errorf("Could not parse `ipaddress` in service %s",
-					service.Name)
+				if ip, err := net.LookupHost(service.IpAddress); err == nil {
+					service.IpAddress = ip[0]
+				} else {
+					return nil, fmt.Errorf("Could not resolve `ipaddress` in service %s",
+						service.Name)
+				}
 			}
 		}
 	}
diff --git a/containerbuddy/config_test.go b/containerbuddy/config_test.go
index 49ea099..a17e67c 100644
--- a/containerbuddy/config_test.go
+++ b/containerbuddy/config_test.go
@@ -246,9 +246,9 @@ func TestInvalidConfigIP(t *testing.T) {
 	defer argTestCleanup(argTestSetup())
 	var testConfig *Config
 	testConfig = unmarshaltestJSON()
-	testConfig.Services[0].IpAddress = "fake"
+	testConfig.Services[0].IpAddress = "#invalid#"
 	tj, _ := json.Marshal(testConfig)
-	testParseExpectError(t, string(tj), "Could not parse `ipaddress` in service serviceA")
+	testParseExpectError(t, string(tj), "Could not resolve `ipaddress` in service serviceA")
 }
 
 func TestInvalidConfigParseFile(t *testing.T) {`

While the previous patches that have been accepted in https://github.com/joyent/containerbuddy/pull/103 are useful, they were meant to completely resolve my use case. But due to the inflexibility of marathon/mesos my initial effort was slightly misplaced - sorry about that.

**Comment by tgross** [comment] 2016-03-10 13:11
Released in https://github.com/joyent/containerbuddy/releases/tag/1.2.0

**Comment by tgross** [comment] 2016-03-10 14:25
I released 1.2.0 this morning in order to fix a bug, but that was before I followed up on this discussion. Given that the patch has been deemed not fit for its original purpose, I've pushed up a PR (https://github.com/joyent/containerbuddy/pull/107) to revert this item and we'll release that as 1.2.1. I'm going to leave this issue open for further discussion, however.

**Comment by misterbisson** [comment] 2016-03-10 16:28
@wleese, from https://github.com/mesosphere/marathon/issues/641#issuecomment-57276924 I see the following:

> If `cmd` is set instead of `args`, then [...] environment variables will expand properly...

I'm seeing the example Marathon task has neither `cmd` nor `args` set, did you test the above?

**Comment by wleese** [comment] 2016-03-10 17:01
> what version of Mesos and Marathon you're using?
Marathon 0.15 and Mesos 0.27

> I'm seeing your example Marathon task has neither cmd nor args set, did you test the above?
I did briefly. Then realized that by doing so I'd run into this problem:

> Caveat: If Containerbuddy is wrapped as a shell command, such as: /bin/sh -c '/opt/containerbuddy .... ' then SIGTERM will not reach Containerbuddy from docker stop

> It would also seem that using --net=host would work correctly
I addressed this in the initial Issue/PR. Bridge networking is not ideal and we will move away from it in the future. Until then however we'd like to make use of containerbuddy.

**Comment by misterbisson** [comment] 2016-03-11 07:09
Because Mesos shells out to run Docker tasks, I misunderstood https://github.com/mesosphere/marathon/issues/641#issuecomment-57276924 to mean that the `/bin/sh -c ...` was in the context of the host/Mesos agent starting the Docker container, not Marathon rewriting the entrypoint or command arguments _to_ the container. On re-reading it, I see my error.

My memory was that I _have_ been able to expand variables named in the `env` section of the `app.json` Marathon task definition, and https://github.com/mesosphere/marathon/issues/1328 seems to confirm it, though you'd referenced it as a non-solution because the host IP appears not to be available as an environment variable in that context, correct?

I do, however, want to re-ask the question about `--net=host` networking, since that does not require any changes to the installed software, and would not affect existing tasks running on the Mesos hosts. I do remember you saying that overlay networking is not an option at this point, but I can't find any mention of  `--net=host`networking before my question above.

Can you say more?

**Comment by wleese** [comment] 2016-03-11 07:48
> you'd referenced it as a non-solution because the host IP appears not to be available as an environment variable in that context, correct?

Correct

> I do, however, want to re-ask the question about --net=host networking

Overlay networking is a term I'm not familiar with. At all times when I inferred any alternative to bridge networking, I meant --net=host.

Some companies simply give you infrastructure to work with, created with compromises so that multiple teams are satisfied. My situation with bridge networking is exactly that. The team providing the Mesos infrastructure is planning a large scale revamp of our network, specifically to allow all our containers to have a BGP advertised IP. 
While this team could put some minor effort in setting up a DHCP server to serve those containers temporarily, they chose to spend their time on the midterm solution (their time already being scarce due to multiple concurrent projects going on).

In the end, those designing containers don't always get the final say in the infrastructure their containers run on :)

**Comment by wleese** [comment] 2016-03-18 12:43
Has some agreement been reached as to what to do with this PR?

**Comment by misterbisson** [comment] 2016-03-18 23:23
@wleese I asked a couple questions in https://github.com/joyent/containerbuddy/pull/108. Hopefully you can understand my concern about scope expansion and the semantic validity of ignoring DNS TTLs. @tgross' point, however, may offer a workaround: injecting the hostname in https://github.com/joyent/containerbuddy/pull/103 (rather than IP, as was expected) may be what you're looking for.

However, if this is truly a short-lived problem, and if your fork is working for you, it might make better sense to continue using the fork. If it's not a short-lived problem, then please consider my question above and those in the PR and give feedback?

Most importantly--especially for a situation like this, something the maintainers' don't have daily need for--the longer you run it in production yourself and the more detail you can bring to documenting the environment, the easier it will be to merge it. A significant reason for wanting that documentation is that I'd be far more comfortable with it if we had enough docs to be able to start up a Mesos cluster that to test this in. My approach to Mesos won't work, https://www.joyent.com/blog/mesos-by-the-pound, so we need something like a set of Packer and Terraform scripts to build up the base image, deploy it on a few VMs, and start Mesos+Marathon+etc.

**Comment by wleese** [comment] 2016-03-21 13:51
>  Hopefully you can understand my concern about scope expansion

An inherent danger of open sourcing your code ;)

> it might make better sense to continue using the fork

For me and you, yes. But perhaps next week someone else will come along who won't have the options I have.

> I'd be far more comfortable with it if we had enough docs to be able to start up a Mesos cluster to test this on

If time permits, I'll give this a go using terraform.

**Comment by wleese** [comment] 2016-03-24 15:17
Looking at the simplicity of this change, would that terraform/mesos testing infra still be needed?

**Comment by misterbisson** [comment] 2016-03-25 16:20
@wleese Thank you for addressing the questions in https://github.com/joyent/containerbuddy/pull/108 . Are those changes now working in production in your environment? Can you share a Marathon task manifest that you're using?

**Comment by wleese** [comment] 2016-03-29 13:13
from the marathon api:

```
{
    "apps": [
        {
            "acceptedResourceRoles": null,
            "args": null,
            "backoffFactor": 1.15,
            "backoffSeconds": 1,
            "cmd": null,
            "constraints": [],
            "container": {
                "docker": {
                    "forcePullImage": true,
                    "image": "rexxxb:2.0.0",
                    "network": "BRIDGE",
                    "parameters": [],
                    "portMappings": [
                        {
                            "containerPort": 8080,
                            "hostPort": 0,
                            "protocol": "tcp",
                            "servicePort": 10001
                        }
                    ],
                    "privileged": false
                },
                "type": "DOCKER",
                "volumes": []
            },
            "cpus": 0.01,
            "dependencies": [],
            "deployments": [],
            "disk": 0.0,
            "env": {
                "APPLICATION": "xxxx",
                "CONSUL_HTTP_TOKEN": "xxxx",
                "ENVIRONMENT": "tst",
                "KEVLAR_ENABLED": "false",
                "KIND": "tst",
                "MEMORY": "512.0",
                "NODE_NUMBER": "0",
                "REDIS_SERVERS": "xxx",
                "STATSD_SERVER": "xxx"
            },
            "executor": "",
            "fetch": [],
            "healthChecks": [],
            "id": "/tst-xxx-tst/0",
            "instances": 1,
            "ipAddress": null,
            "labels": {},
            "maxLaunchDelaySeconds": 3600,
            "mem": 512,
            "ports": [
                10001
            ],
            "requirePorts": false,
            "storeUrls": [],
            "tasksHealthy": 0,
            "tasksRunning": 1,
            "tasksStaged": 0,
            "tasksUnhealthy": 0,
            "upgradeStrategy": {
                "maximumOverCapacity": 1,
                "minimumHealthCapacity": 0.5
            },
            "uris": [],
            "user": null,
            "version": "2016-03-24T12:14:12.984Z",
            "versionInfo": {
                "lastConfigChangeAt": "2016-03-24T12:14:12.984Z",
                "lastScalingAt": "2016-03-24T12:14:12.984Z"
            }
        }
    ]
}
```

in the container:
```
[root@576a11da6335 /]# env | grep HOST
HOSTNAME=576a11da6335
HOST=tst-mesos-master-xxx.xxxxxxx.xxx
[root@576a11da6335 /]# cat /opt/containerbuddy/app.json 
{
  "consul": "{{.HOST}}:8500",
  "stopTimeout": -1,
  "services": [
    {
      "name": "{{.ENVIRONMENT}}-{{.APPLICATION}}-{{.KIND}}",
      "port": 8080,
      "address": "{{.HOST}}",
      "health": "/usr/bin/curl --fail -s -o /dev/null http://localhost:8080",
      "poll": 10,
      "ttl": 30
    }
  ]
}
```

The consul agent on $HOST (the mesos machine the docker container is running on) listens on 0.0.0.0:8500 and as such is available to containerbuddy

**Comment by misterbisson** [comment] 2016-03-30 15:18
@wleese is the above working in production now?

**Comment by wleese** [comment] 2016-03-30 15:21
Correct

**Comment by micahlmartin** [comment] 2016-04-20 18:08
+1 on this or something like it. We're not yet running overlay networking on our docker cluster but we we are on AWS. What I'd like to do is be able to use the aws metadata service from within the container to discover the IP of the host it's running on and dynamically inject that into the containerpilot configuration like @wleese is doing. The difference being that I need to be able to do it from inside the container at run-time and not inject it into container from the orchestration side.

**Comment by tgross** [comment] 2016-04-20 18:24
@micahlmartin we've got a PR open and are still trying to get it across the finish line: https://github.com/joyent/containerpilot/pull/108

**Comment by tgross** [comment] 2016-04-22 14:10
Once we get a green build on master back from TravisCI, I'll cut release 2.1.0 with this in it.

**Comment by tgross** [comment] 2016-04-22 14:24
https://github.com/joyent/containerpilot/releases/tag/2.1.0

**Closed by tgross** 2016-04-22 14:24 UTC
Labels: enhancement, released
