### ISSUE TITLE
Nginx not reloading with many services starting up together

### ISSUE THREAD

**Issue by thefosk** [joyent/containerpilot#216] opened 2016-08-31 18:09 UTC
Sometimes when there are many services starting up and registering themselves to Consul at the same time (like 6/7 services), it seems like Nginx doesn't properly reload to regenerate the configuration every time, and I need to manually trigger a `docker restart CONTAINER_ID` in order to force Nginx to re-generate the correct configuration after all the services are finally up and running.

Is anybody else dealing with this issue?

**Comment by fitz123** [comment] 2016-08-31 18:14
What is your configuration?
Are you using "Backend" or directly consul-template for templates generation? These multiple services are in same container or not?
Please share details. I have configuration with dozens of servers and all templates are fine, nginx restarts correctly

**Comment by thefosk** [comment] 2016-08-31 18:42
I have the following Docker Compose configuration for Consul/Nginx:

```yaml
nginx-lb:
  build: nginx/
  mem_limit: 128m
  ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
    - 3001:3001
    - 10000:10000
    - 10001:10001
    - 10002:10002
    - 10003:10003
  expose:
    - 8000
    - 8443
    - 8001
    - 3001
    - 10000
    - 10001
    - 10002
    - 10003
  links:
    - consul:consul
  restart: always
  command: >
      /bin/containerpilot
      -config file:///etc/containerpilot/containerpilot.json
      nginx -g "daemon off;"

consul:
  image: progrium/consul:latest
  command: -server -bootstrap -ui-dir /ui
  restart: always
  mem_limit: 128m
  ports:
    - 8500:8500
  expose:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
  dns:
    - 127.0.0.1

# All the services definitions are below here
# ....
```

And each service has a `containerpilot.json` similar to:

```
{
  "consul": "consul:8500",
  "services": [
    {
      "name": "hello-world",
      "port": 8080,
      "health": "/usr/bin/curl -s -o /dev/null http://localhost:8080/",
      "poll": 3,
      "ttl": 10
    }
  ]
}
```

## Nginx

The Nginx server has the following `containerpilot.json` configuration:

```json
{
  "consul": "consul:8500",
  "preStart": "/bin/reload-nginx.sh preStart",
  "logging": {
    "level": "DEBUG",
    "format": "text"
  },
  "services": [
    {
      "name": "nginx",
      "port": 80,
      "interfaces": ["eth1", "eth0"],
      "health": "/usr/bin/curl -o /dev/null --fail -s http://localhost/health",
      "poll": 10,
      "ttl": 25
    }
  ],
  "backends": [
    {
      "name": "service-8000",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    },
    {
      "name": "service-8443",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    },
    {
      "name": "service-8001",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    },
    {
      "name": "service1",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    },
    {
      "name": "service2",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    },
    {
      "name": "service3",
      "poll": 4,
      "onChange": "/bin/reload-nginx.sh onChange"
    }
  ]
}
```

The following `nginx.conf.ctmpl` template:

```nginx
user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 65536;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    charset UTF-8;

    server {
        listen 80;
        location /health {
            # requires http_stub_status_module
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
}

stream {
    {{range services}}
    upstream {{.Name}} {
        least_conn;{{range service .Name}}
        server {{.Address}}:{{.Port}} max_fails=3 fail_timeout=60 weight=1;{{else}}
        server 0.0.0.1:80; # invalid placeholder{{end}}
    }{{range $index, $element := service .Name}}{{if eq $index 0}}
    server {
        listen {{.Port}};
        proxy_pass {{.Name}};
    }
    {{end}}{{end}}{{end}}
}
```

and the following `reload-nginx.sh` script:

```shell
#!/bin/sh

# Render Nginx configuration template using values from Consul,
# but do not reload because Nginx has't started yet
preStart() {
    consul-template \
        -once \
        -consul consul:8500 \
        -template "/etc/containerpilot/nginx.conf.ctmpl:/etc/nginx/nginx.conf"
}

# Render Nginx configuration template using values from Consul,
# then gracefully reload Nginx
onChange() {
    consul-template \
        -once \
        -consul consul:8500 \
        -template "/etc/containerpilot/nginx.conf.ctmpl:/etc/nginx/nginx.conf:nginx -s reload"
}

until
    cmd=$1
    if [ -z "$cmd" ]; then
        onChange
    fi
    shift 1
    $cmd "$@"
    [ "$?" -ne 127 ]
do
    onChange
    exit
done
```

**Comment by fitz123** [comment] 2016-08-31 19:06
I'd suggest you to try run consul-template as a coprocess instead of these millions backend records. I guess this backends just rewriting each other when Change happens.
If you wanna keep these setting (with a lot of backends) you need to create a template per backend

**Comment by thefosk** [comment] 2016-08-31 19:08
> try run consul-template as a coprocess

I can give it a try - any documentation reference you can point me to?

**Comment by fitz123** [comment] 2016-08-31 19:10
Also try keep these but add "wait" option to consul-template, like this:

```
onChange() {
    consul-template \
        -once \
        -wait 5s:10s \
        -consul consul:8500 \
        -template "/etc/containerpilot/nginx.conf.ctmpl:/etc/nginx/nginx.conf:nginx -s reload"
```

It may fix the issue right away. But still I'd use coprocess in this case

**Comment by tgross** [comment] 2016-08-31 19:11
> Sometimes when there are many services starting up and registering themselves to Consul at the same time (like 6/7 services), it seems like Nginx doesn't properly reload to regenerate the configuration every time, and I need to manually trigger a docker restart CONTAINER_ID in order to force Nginx to re-generate the correct configuration after all the services are finally up and running.

Hm, this *should* settle out. If after it gets "stuck" and you then add a new instance of any of the backend services does it then complete the reconfiguration for all instances? Have to verified that `consul-agent` is running to completion without error? Can you check the results of `nginx -test` with the rendered config file?

> I can give it a try - any documentation reference you can point me to?

Example here: https://github.com/autopilotpattern/nginx/blob/master/etc/containerpilot.json#L23-L29

**Comment by fitz123** [comment] 2016-08-31 19:11
There's an example of running consul-template as a coprocess: https://www.joyent.com/containerpilot/docs/configuration

**Comment by thefosk** [comment] 2016-08-31 21:02
Just to clarify this point, if I run consul as a coprocess, do I still need to explicitly list the backend services or I can remove them from the Nginx's `containerpilot.json` configuration?

**Comment by fitz123** [comment] 2016-09-01 10:13
@thefosk, in this case you can remove them, since your consul-template monitors all services anyway, because "{{range services}}" in configuration

**Comment by tgross** [comment] 2016-09-01 12:09
The example in our configuration has Consul Agent running as a co-process, not consul-template. If you were to run consul-template as a coprocess you can elide the `backends` section in the `containerpilot.json` config only if _both_ the following are true:
- you only need to do the template reconfiguration in Nginx and no other task when a backend changes
- you can filter the `{{ range services }}` to cover only the services you want or hand-code the service names; _all_ services you have registered with Consul will end up in that range.

**Comment by tgross** [comment] 2016-09-01 12:10
Also, it still sounds like you may have stumbled into a possible bug and rather than working around it I'd like to fix it. Answering the questions in https://github.com/joyent/containerpilot/issues/216#issuecomment-243869291 will help me figure out if this is the case.

**Comment by thefosk** [comment] 2016-09-01 17:57
@tgross 

```
# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by tgross** [comment] 2017-05-22 20:48
I should have closed this issue a while back. The problem was the lack of a filter on the `{{ range services }}`, which turned out to bit me again in an integration test as described in: https://github.com/joyent/containerpilot/issues/372

**Closed by tgross** 2017-05-22 20:48 UTC
Labels: needs more info, v2

**Comment by andersfylling** [comment] 2018-12-13 23:07
I feel this might be related to my own issue. I've tried with both version 3 and 3.8 now and yes I'm running in Docker 18.09.
first issue, just to mention it: when doing `exec: 'nginx -g "daemon off;"',` I get the error that off is not a valid argument so I have to do `exec: "./start-nginx.sh",` which holds `nginx -g "daemon off;"` and execute then successfully.

Anyways, I'm starting up nginx as a job and trying to run consul-template along side nginx. Just as op.
```json
{
  consul: "consul-server:8500",
  jobs: [
    {
      name: "gateway",
      when: {
        source: "preStart",
        once: "exitSuccess"
      },
      exec: "./start-nginx.sh",
      port: 80,
      health: {
        exec: "/usr/bin/curl -o /dev/null --fail -s http://localhost/nginx-health",
        interval: 5,
        ttl: 10,
        timeout: "5s"
      },
      tags: [
        "gateway"
      ]
    },
    {
      name: "preStart",
      exec: [
        "consul-template",
        "-once",
        "-consul-addr", "consul-server:8500",
        "-template", "./templates/server.conf.ctmpl:/etc/nginx/conf.d/server.conf"
      ]
    },
    {
      name: "gateway-router",
      exec: "consul-template -once -config config.hcl",
      when: {
        source: "watch.app",
        each: "changed",
      }
    }
  ],
  watches: [
    {
      name: "app",
      interval: 5
    }
  ]
}
```

nginx starts, and the healh checks work as my container shows up in the consul dashboard. I can confirm that after several tries of rewriting and tweaking this, I have had 0 success of getting consul-template to run.

I've also changed my start-nginx script to verify that nginx hasn't crashed and even if that runs as `nohup ./start-nginx.sh &`, I still cannot get the other job to work.
