### ISSUE TITLE
NPE in waitForTimeout in 2.7.0

### ISSUE THREAD

**Issue by ngarratt** [joyent/containerpilot#351] opened 2017-05-11 22:08 UTC
We're getting an intermittent panic during container registration (Consul 0.7.5)

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4e4b28]

goroutine 22 [running]:
panic(0xb534e0, 0xc8200140a0)

/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/joyent/containerpilot/commands.(*Command).waitForTimeout(0xc820077080, 0x0, 0x0)
        /cp/src/github.com/joyent/containerpilot/commands/commands.go:212 +0x798
github.com/joyent/containerpilot/commands.RunWithTimeout(0xc820077080, 0xc8202049f0, 0x0, 0x0)
        /cp/src/github.com/joyent/containerpilot/commands/commands.go:150 +0x53c
github.com/joyent/containerpilot/services.(*Service).CheckHealth(0xc8200ba600, 0x0, 0x0)
        /cp/src/github.com/joyent/containerpilot/services/services.go:183 +0x23c
github.com/joyent/containerpilot/services.(*Service).PollAction(0xc8200ba600)
        /cp/src/github.com/joyent/containerpilot/services/services.go:149 +0x21
github.com/joyent/containerpilot/core.(*App).poll.func1(0xc8201515c0, 0xc8200862a0, 0x7fcafbbe9470, 0xc8200ba600, 0xc820017c20)
        /cp/src/github.com/joyent/containerpilot/core/poll.go:15 +0xbf
created by github.com/joyent/containerpilot/core.(*App).poll
        /cp/src/github.com/joyent/containerpilot/core/poll.go:22 +0xab

We only see this where we're doing concurrent activation of multiple instances of the same container on the same host. After a few die/respawn cycles they start up correctly (after their startup times have drifted apart).

This is on ECS, so we're introspecting IP/port information during preStart and sending a HUP to containerpilot.

**Comment by tgross** [comment] 2017-05-12 13:10
Looks like the panic is happening at [this line](https://github.com/joyent/containerpilot/blob/46b0387ff72f9288fc7080d48af2356b799f84d7/commands/commands.go#L212), which is [this line](https://github.com/joyent/containerpilot/blob/62fd85227c56abc746ed4d5ba56d9cf61a5aba89/commands/commands.go#L215) in the 2.7.3 current version.

The NPE is getting hit when the process exits before we wait for it; we've recently merged some fixes in 2.7.3 that help out with warnings during reaping but missed this. If we check nil before writing the log we'll have a [TOCTOU](https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use) bug, but these are really just debug log lines so it's probably easiest just to drop the log line. I'll sweep thru the rest of that package and make sure we don't have other examples.

**Comment by ngarratt** [comment] 2017-05-12 22:56
In this case the process is still running at the time of the NPE

To confirm that, I set supervisord to restart containerpilot (startretries=2). After the panic, we see it starting up again, but this time the application throws out a bind error (ERROR: transport error 202: bind failed: Address already in use) because the initial process is still running on that port.

The script containerpilot is set to use for startup invokes exec to run java, so there should be no PID issues there.

**Comment by ngarratt** [comment] 2017-05-14 21:11
I've narrowed this down to blocking health checks.

When we HUP containerpilot after introspection is complete (T+5 seconds), we end up with two health checks running. One of them runs with the settings originally defined in containerpilot.json, the other with any settings changed by introspection. This is probably not related to the issue here (I can open another issue to track if you prefer) - just including it here for reference.

These health checks (just curl) will block until the application has finished bootstrap and is connected to Cassandra (T+40s). They have poll of 10s, but no timeout in containerpilot.

For a working startup - they both return success from the first health check after C* is connected (T+45s), and then health checks (both of them) continue at the normal poll interval

For a failed startup - they both return success after C*is connected, but immediately throw the NPE when they try to kick again.

Changing the health check to timeout (rather than block) works around the NPE. As long as that initial health check fails at least once before it succeeds, we don't have any NPE events. It doesn't have to fail within the poll interval for the health check (so setting curl to timeout after either 9s or 11s works to avoid the issue)

This was tested with both 2.7.0 and 2.7.3

**Comment by tgross** [comment] 2017-05-15 12:47
Ok, there's a lot to unpack here.

> When we HUP containerpilot after introspection is complete (T+5 seconds), we end up with two health checks running. One of them runs with the settings originally defined in containerpilot.json, the other with any settings changed by introspection. One of them runs with the settings originally defined in containerpilot.json, the other with any settings changed by introspection. This is probably not related to the issue here (I can open another issue to track if you prefer) - just including it here for reference.

Actually I suspect this is the heart of the problem. We don't really have a way (in CPv2) to stop a running health check on SIGHUP. What it sounds like is that the original health check process is continuing to run after the SIGHUP but the `Command` struct that it's returning information to has been destroyed by that point. If you could provide the stack trace from your test with CPv2.7.3 it might help to debug what we can do about that.

---

Addressing some of the unrelated issues:

> To confirm that, I set supervisord to restart containerpilot (startretries=2). After the panic, we see it starting up again, but this time the application throws out a bind error (ERROR: transport error 202: bind failed: Address already in use) because the initial process is still running on that port.

This is the incorrect behavior; once ContainerPilot exits (for any reason), your supervisor should be reaping the whole process tree, not restarting ContainerPilot without reaping all children first.

> The script containerpilot is set to use for startup invokes exec to run java, so there should be no PID issues there.

I'm going to need some more information about what you're doing here. It looks like you're not running ContainerPilot as PID1, and you're not running the Java process as a direct child of ContainerPilot either. Which isn't really the intended model, so I'm not surprised you're running into corner cases with the child reaping.

> These health checks (just curl) will block until the application has finished bootstrap and is connected to Cassandra (T+40s). They have poll of 10s, but no timeout in containerpilot.

We couldn't add default timeouts to healthchecks without breaking backwards compatibility, so this was added in v3. You should _definitely_ have a timeout if you've got a long setup like this.

**Comment by tgross** [comment] 2017-05-15 16:49
Also, have you tried the code in https://github.com/joyent/containerpilot/pull/352?

**Comment by ngarratt** [comment] 2017-05-15 18:45
We don't normally run restarts in the supervisor - if CP fails to start we just terminate the container. It was only added to validate that the java process was still running and hadn't terminated quickly.

Coprocessors didn't give us enough control over secondary processes, so we run supervisord as PID1 calling CP as one of its services. CP is running java processes, which always need a significant number of environment variables. So it's set to execute a script that sets everything up, and then calls "exec java ...". So java is a direct child of CP.

Bask to the core issue here, what interesting is that in most cases we didn't have any issue with these health checks. Both continued to fire, and both were able to set the service healthy/unhealthy (so control structures for the first are not completely orphaned by the post-HUP one).

I don't have any issues with setting timeouts on all services, and having two health checks running until v3 is out

Here is the trace from 2.7.3

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4e4547]

goroutine 34 [running]:
panic(0xb521a0, 0xc8200140b0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/joyent/containerpilot/commands.(*Command).waitForTimeout(0xc82008f180, 0x0, 0x0)
        /cp/src/github.com/joyent/containerpilot/commands/commands.go:215 +0x857
github.com/joyent/containerpilot/commands.RunWithTimeout(0xc82008f180, 0x0, 0x0)
        /cp/src/github.com/joyent/containerpilot/commands/commands.go:153 +0x4d4
github.com/joyent/containerpilot/services.(*Service).CheckHealth(0xc8200d4780, 0x0, 0x0)
        /cp/src/github.com/joyent/containerpilot/services/services.go:185 +0x53
github.com/joyent/containerpilot/services.(*Service).PollAction(0xc8200d4780)
        /cp/src/github.com/joyent/containerpilot/services/services.go:150 +0x21
github.com/joyent/containerpilot/core.(*App).poll.func1(0xc82000b9c0, 0xc8200a02a0, 0x7f161a97e848, 0xc8200d4780, 0xc820017380)
        /cp/src/github.com/joyent/containerpilot/core/poll.go:15 +0xbf
created by github.com/joyent/containerpilot/core.(*App).poll
        /cp/src/github.com/joyent/containerpilot/core/poll.go:22 +0xab

**Comment by tgross** [comment] 2017-05-15 19:13
> Coprocessors didn't give us enough control over secondary processes, so we run supervisord as PID1 calling CP as one of its services. CP is running java processes, which always need a significant number of environment variables. So it's set to execute a script that sets everything up, and then calls "exec java ...". So java is a direct child of CP.

That makes sense. The weakness of the coprocess implementation is behind some of the multiprocess improvements for v3, so I totally understand why you'd go down that path. So long as you have a real supervisor as PID1 that reaps children (as you do with `supervisord`), you should be ok here.

> I don't have any issues with setting timeouts on all services, and having two health checks running until v3 is out

Sure, but this is going to be racy and it's just bad practice on our part to leave the bug in, given our [post-v3 compatibility and support guarantees](https://github.com/joyent/rfd/blob/master/rfd/0086/compat.md#joyent-support). So it seems worth hunting down.

> Here is the trace from 2.7.3

Yeah I realized later that 2.7.3 doesn't include the changes in https://github.com/joyent/containerpilot/pull/352 neglected to go back and edit the question. This is panicking right [here](https://github.com/joyent/containerpilot/blob/v2_backports/commands/commands.go#L215), which is the same location that the 2.7.0 code did. I built #352 and uploaded it to Manta here: https://us-east.manta.joyent.com/timgross/public/containerpilot/containerpilot-37ca3e7-dev.tar.gz  So if you want to give that a try?

**Comment by ngarratt** [comment] 2017-05-18 22:16
While preparing to test, we hit another, more serious, issue.

We started having issues where containers were registering the service into Consul using pre-HUP definitions. We change both IP and port to their external representation as part of introspection, but started seeing clusters of services registering their internal state instead (breaking connectivity between some services in one of our test environments).

I would guess the health checks retain the definition of the service at the time they are instantiated, and so we have a different type of race. Before we added the timeouts, they would always queue in a specific order, and so we were (accidentally) seeing the results we expected. After the timeouts were added, the 'winner' would be pseudo-random (based on the time the service takes to become healthy)

As a workaround, supervisord was modified to call a shim that performs the introspection and then does an exec against CP. This allows us to avoid the preStart/HUP entirely, which is the root of all these issues. 

I can test #352 if you want, but this looks like a larger issue that may be better tackled in 3.x

**Comment by tgross** [comment] 2017-05-19 13:03
> We started having issues where containers were registering the service into Consul using pre-HUP definitions. We change both IP and port to their external representation as part of introspection, but started seeing clusters of services registering their internal state instead (breaking connectivity between some services in one of our test environments).

I'm not sure I understand what the "external" vs "internal" state is here. It sounds very much like you've got some kind of workaround of NAT going on here, which is not recommended and unsupported. It would be very helpful if you were able to provide your ContainerPilot configuration and behavior scripts if possible.

> I would guess the health checks retain the definition of the service at the time they are instantiated, and so we have a different type of race.

Before we try to diagnose the problem we really need to understand the behavior you're seeing. I suspect you may be hitting some variant of https://github.com/joyent/containerpilot/issues/264 but until I know what behavior you're seeing I can't be sure.

> I can test #352 if you want

I don't have a reproduction unless you do, so otherwise I'll merge that PR and cut the patch and then close this issue.

**Comment by ngarratt** [comment] 2017-05-30 14:40
Yes, there is NAT involved here (there is a requirement for both external direct-addressability and multiple containers on a single host). If it's unsupported, then this issue can be closed.

For reference, I was following #181. Our preStart changes the CP interface definition from eth0 (docker local bridge on 172.17.0.0/24) to a public IP, and also modifies the service port. That all happens before CP runs now, so it's only ever aware of the public IP/port

**Comment by tgross** [comment] 2017-05-30 14:55
> Yes, there is NAT involved here (there is a requirement for both external direct-addressability and multiple containers on a single host)

You should be using overlay networking of some kind (VXLAN) or using host networking and taking advantage of the scheduler to assign ports.

> For reference, I was following #181. Our preStart changes the CP interface definition from eth0 (docker local bridge on 172.17.0.0/24) to a public IP, and also modifies the service port. That all happens before CP runs now, so it's only ever aware of the public IP/port

All of which _should_ work, it's just the most convoluted way to do it.

Without a repro I'm going to merge #352, which we know will fix the NPE in the logs provided. That'll be released as 2.7.4.

**Comment by tgross** [comment] 2017-05-30 15:50
Released as https://github.com/joyent/containerpilot/releases/tag/2.7.4

**Closed by tgross** 2017-05-30 15:50 UTC
Labels: awaiting release, bug, v2
