### ISSUE TITLE
Many <defunct> processes when its parent is killed by containerpilot

### ISSUE THREAD

**Issue by roengram** [joyent/containerpilot#409] opened 2017-06-19 08:12 UTC
Hi,

I'm using containerpilot 2.7.4.
I created a task that executes a shell script periodically, which in turn executes a command.
When the command process takes longer than the timeout configured for the task, containerpilot kills the shell process by sending it SIGKILL. This makes the command process parentless and it eventually becomes <defunct> when finished. Because the task is executed periodically, the number of defunct processes grows until it hits the max process number. 

I've created a tiny demo for clarity: 
[containerpilot.tar.gz](https://github.com/joyent/containerpilot/files/1084207/containerpilot.tar.gz)
The task just invokes sleep longer than its timeout. Several minutes after launching the demo with "docker-compose up --build", you can observe many defunct sleep processes. I also included log file.

Prefferably, I think containerpilot should kill the entire process tree of a timedout task. Alternatively, contaierpilot should send a signal other than SIGKILL so that users can specify trap for the signal.

**Comment by tgross** [comment] 2017-06-19 12:34
Thanks for the report, @roengram. This is definitely a bug.

ContainerPilot should be reaping the whole process group. I checked on the code and we're [doing it correctly in v3](https://github.com/joyent/containerpilot/blob/837b3ab63142394f885217a128520bf329f11634/commands/commands.go#L140). But somehow this never made its way [back to v2](https://github.com/joyent/containerpilot/blob/c45436a725458c4ead0c6ec1ac5a06b7e77d06e5/commands/commands.go#L175)

Thanks for providing such a clear reproduction! This should be an easy fix and I'll get right on this.

**Comment by tgross** [comment] 2017-06-19 12:39
Just for the record it looks like this was introduced in 2.7.3 in https://github.com/joyent/containerpilot/pull/334. Simply sending SIGTERM to the top-level command process was fine before that because we had a general SIGCHLD signal handler. By introducing the reaper code that wasn't going to work anymore.

**Comment by tgross** [comment] 2017-06-19 13:10
Opened https://github.com/joyent/containerpilot/pull/410

**Comment by tgross** [comment] 2017-06-19 13:35
Not only is this an issue for v2 but I've also been able to confirm it's an issue in v3 now too. ☹️

**Comment by tgross** [comment] 2017-06-19 13:50
We have an integration test that should be catching this, so I've had a look at that. It looks like unfortunately the test is simply wrong. Here's what I get if I echo the outputs of `test_reap_zombies/run.sh`:

```
2017/06/19 09:49:34 TEST: test_reap_zombies
STAT PPID  PID   COMMAND
S        0     1 containerpilot
S        1    10 tail
Z        1    16 sleep
Z        1    19 sleep
Z        1    21 sleep
Z        1    23 sleep
Z        1    25 sleep
Z        1    27 sleep
S        1    28 sleep
Z       28    29 sleep
R        0    30 ps
REPARENTED_ZOMBIES: 0
TOTAL_ZOMBIES: 0
2017/06/19 09:49:53 PASS: test_reap_zombies
```

There are 6 reparented zombies and 7 total zombies, but we're not catching that in the `awk` expression. So first thing to do is to fix the test so that it fails correctly.

**Comment by tgross** [comment] 2017-06-19 14:00
With [this updated test](https://github.com/joyent/containerpilot/blob/602f12cb5285fd5d2bbe3e4899731395d7648cdb/integration_tests/tests/test_reap_zombies/run.sh) I have a correctly-failing test now:

```
2017/06/19 09:59:40 TEST: test_reap_zombies
More than permitted number of zombies.
- got 6 reparented zombies
- got 6 total zombies
STAT PPID  PID   COMMAND
S        0     1 containerpilot
S        1    11 tail
Z        1    17 sleep
Z        1    20 sleep
Z        1    22 sleep
Z        1    24 sleep
Z        1    26 sleep
Z        1    28 sleep
S        1    29 sleep
S       29    30 sleep
R        0    31 ps
2017/06/19 09:59:59 FAIL: test_reap_zombies
2017/06/19 10:00:01 ==== Tests Failed! ====
```

**Comment by tgross** [comment] 2017-06-19 15:00
Ok, I've got fixes open in #410 and #411 and I've been able to confirm that it fixes the problem in the repro you've provided.

**Comment by tgross** [comment] 2017-06-23 14:39
Fixed in https://github.com/joyent/containerpilot/releases/tag/3.1.0 and Released in https://github.com/joyent/containerpilot/releases/tag/2.7.5

**Closed by tgross** 2017-06-23 14:39 UTC
Labels: awaiting release, bug, v2, v3.x

**Comment by roengram** [comment] 2017-07-25 04:34
Hi, I've found the same issue occurring when I was using curl instead of sleep.
I used containerpilot 2.7.6 and let containerpilot periodically executes a script with 1 sec timeout.
The script executes curl to get from 1.2.3.4/index.htm. Because there's no such document, curl freezes more than 1sec, making containerpilot kills it. I could observe <defunct> curl process stacking up.
I still don't know if this is containerpilot issue. This may be because the way I made the recurring script.

Please find an attachement for reproduction. Please ignore the misleading name of "sleeper". It's actually "curl-er".
[containerpilot.tar.gz](https://github.com/joyent/containerpilot/files/1171960/containerpilot.tar.gz)
