### ISSUE TITLE
Health Checks does not support Consul's warning state

### ISSUE THREAD

**Issue by therealgambo** [joyent/containerpilot#302] opened 2017-04-02 21:00 UTC
When registering a service health check (using curl for the check) if the response is a `429 Too Many Requests` this should be updated in Consul putting the service into a "warning" state.

It looks like at the moment anything other than a `200 OK` results in a failure, which updates Consul  putting the service into a "critical" state.

 If the "deregisterCriticalService" configuration has been set, then the service will be unnecessarily removed because it has been marked as "critical" by mistake.

**Comment by tgross** [comment] 2017-04-03 12:27
This is by design @therealgambo. ContainerPilot only responds to the exit code of the health check. 

We respond only to the exit code because ContainerPilot doesn't know how to parse arbitrary outputs of the health checks and we need to support non-HTTP services (ex. databases). The "API" that the health code is asked to fulfill is boolean -- is the service healthy or not? We've intentionally chosen not to support the "warning" state because it doesn't tell us anything we can use for service discovery.

In this specific case `curl` only returns a non-zero exit code in the case where it encounters an error or if the `--fail` option is used with a 4xx HTTP status code. So `curl` doesn't have a way of telling us if it encountered `429 Too Many Requests` even if we were paying attention to that detail.

**Comment by therealgambo** [comment] 2017-04-12 02:52
All of that makes perfect sense @tgross. Perhaps we could update the documentation to mention that the warning state in consul is not supported at this time.

While putting a service into a warning state won't offer much in terms of service discovery, it does provide visibility on the health of the service which is essential when using external monitoring tools and monitoring policies.

Having a service be fine one minute, then jumping to critical seems like a quite a drastic action when the true health of the service is not in a critical state. If dependent services are following the health of a service, this has the potential to create a cascading service failure.

Is it possible in the mean time to check the return codes of a script? At least that way we can make the request, the users script (shell, python, php, etc..) can interpret the response and return the appropriate return code.

**Comment by tgross** [comment] 2017-04-12 12:31
> While putting a service into a warning state won't offer much in terms of service discovery, it does provide visibility on the health of the service which is essential when using external monitoring tools and monitoring policies.

See https://github.com/joyent/containerpilot/issues/154 and [RFD86](https://github.com/joyent/rfd/blob/master/rfd/0086/mariposa.md) for how this will be covered.

> Having a service be fine one minute, then jumping to critical seems like a quite a drastic action when the true health of the service is not in a critical state.

For the purposes of service discovery, which is the purpose of ContainerPilot health checks and registration with Consul, this is exactly what you want. How your application responds when services are in a degraded state is out of scope.

**Closed by tgross** 2017-04-12 12:31 UTC
Labels: usage
