### ISSUE TITLE
health checks always hit timeout when returning non 0

### ISSUE THREAD

**Issue by commarla** [joyent/containerpilot#233] opened 2016-10-19 20:31 UTC
Hi,

I am using this simple health script 

```
#!/bin/bash

state=$(curl -s localhost:4000/v1.24/info|jq -r 'select(.SystemStatus[0][1]=="primary")|.SystemStatus[0][1]')

if [ "$state" == "primary" ]; then
        echo "I was elected primary :fu:"
        exit 0
else
        echo "I am a simple replica :'("
        exit 255
fi
```

It checks if the node is primary or replica in docker swarm cluster and only the primary is registered in consul.

It is working fine but I have this strange behavior when the script return 255 

> 2016/10/19 22:22:00 I am a simple replica :'(
> 2016/10/19 22:22:02 swarm-manager.health timeout after 2s: '[]'
> 2016/10/19 22:22:02 killing command at pid: 1129
> 2016/10/19 22:22:02 error killing command: os: process already finished
> 2016/10/19 22:22:10 I am a simple replica :'(
> 2016/10/19 22:22:12 swarm-manager.health timeout after 2s: '[]'
> 2016/10/19 22:22:12 killing command at pid: 1135
> 2016/10/19 22:22:12 error killing command: os: process already finished

Containerpilot always hit the timeout.
On the other side if the return code is 0, I have no log 

> 2016/10/19 22:27:20 I was elected primary :fu:
> 2016/10/19 22:27:30 I was elected primary :fu:
> 2016/10/19 22:27:40 I was elected primary :fu:

My containerpilot.json
```
{
  "consul": "{{ .CONSUL_ADDRESS }}",
  "logging": {
    "level": "INFO",
    "format": "default",
    "output": "stdout"
  },
  "stopTimeout": 5,
  "services": [
    {
      "name": "swarm-manager",
      "port": 4000,
      "health": [
        "/usr/local/bin/health.sh"
      ],
      "interfaces": [
        "inet"
      ],
      "poll": 10,
      "ttl": 30,
      "timeout": "2s",
      "tags": ["docker", "swarm", "swarm-manager"]
    }
  ]
}
```

Containerpilot v2.4.3

> root@preprod-swarm-manager:/# /usr/local/bin/containerpilot -version
> Version: '2.4.3'
> GitHash: '8b825e2'

Regards,

Laurent

**Comment by fitz123** [comment] 2016-10-20 01:28
I'm not a CP developer, but 
My assumption'd be that CP expects 0 as an health check. Any other exit code basically could mean that something wrong could happen during health check and safer to make sure this something is killed afterwards. I think it's a feature, not a bug =) 
I'd say it's a wrong solution to treat a "bad" health check result as a meaningful/good event.
It other words, you're using swarm's primary/replica check against localhost to publish it into the consul, but the _origin_ of this info is actually already in there: http://consul:8500/v1/kv/docker/swarm/leader

If you could explain what do you need it for (since you can use any of swarm-managers to execute swarm API calls), I can probably suggest a better solution

**Comment by commarla** [comment] 2016-10-20 08:51
Thanks for your answer.

I am using this to have only one IP returned on DNS query (swarm-manager.service.consul). 

And I was not aware than I can request the slave as well so I don't need this at all.

Anyway I am interested by the enableTagOverride option, is there a way to enable it with CP ?
If I am able to add tag to consul this option is better as I can use <tag>.swarm-manager.service.consul.

**Comment by fitz123** [comment] 2016-10-20 11:41
If you swarm-managers have dynamically IPs, you can use your service definition as it is now. Everything should work just fine when IPs from all nodes are returned. In this particular case there's no reason to tag primary/replica managers. In other words, you already can use your "swarm-manager.service.consul" address, just replace check by something else, for example: `health": ["curl", "--fail", "--silent", "--show-error", "--output", "/dev/null", "http://localhost:4000"]`

**Comment by tgross** [comment] 2016-10-20 12:43
@commarla thanks for the thorough report! I agree that the behavior you're seeing doesn't look right. Is the service still being marked unhealthy as expected in that case? Could you run this with debug logging on (`"logging": {"level": "DEBUG"}`)? I suspect we're just failing to send the "I'm done" signal to the timeout code when we're done, but I want to make sure I'm not missing anything.

@fitz123 wrote:
> I feel like it's a wrong solution to treat a "bad" health check result as a meaningful/good event.

From a design perspective I totally agree on this.

**Comment by tgross** [comment] 2016-10-20 13:15
@commarla I've been able to reproduce what you're seeing by modifying [`TestRunWithTimeoutFailed`](https://github.com/joyent/containerpilot/blob/8b825e2377ef2d803e003dd02fc1b3f21c568317/commands/commands_test.go#L80-L86).

```go
func TestRunWithTimeoutFailed(t *testing.T) {
	cmd, _ := NewCommand("./testdata/test.sh failStuff --debug", "1s")
	fields := log.Fields{"process": "test"}
	start := time.Now()
	if err := RunWithTimeout(cmd, fields); err == nil {
		t.Errorf("Expected error but got nil")
	}
	elapsed := time.Since(start)
	time.Sleep(2 * time.Second)
	t.Errorf("%v", elapsed)
}
```

which results in:

```
=== RUN   TestRunWithTimeoutFailed
time="2016-10-20T13:09:04Z" level=info msg="Running failStuff with args: --debug" process=test
time="2016-10-20T13:09:05Z" level=warning msg="./testdata/test.sh timeout after 1s: '[failStuff --debug]'"
time="2016-10-20T13:09:05Z" level=warning msg="killing command at pid: 452"
time="2016-10-20T13:09:05Z" level=error msg="error killing command: os: process already finished"
--- FAIL: TestRunWithTimeoutFailed (2.02s)
        commands_test.go:91: 11.354752ms
```

What's looks to be happening is that control flow is returning to the poll loop, and the TTL heartbeat isn't being sent -- just as expected. Health checks will fail in the case as we expect them to and the behavior of your heartbeats will work fine.

But we're leaving a goroutine running and then when it gets cleaned up by the timeout it throws the error and we get the log noise you're seeing. This was probably introduced by me in in PR #224 when we fixed a bug in the timeout. I _think_ (but haven't yet verified) that we can fix this by moving [this block](https://github.com/joyent/containerpilot/pull/224/files#diff-b54b33b58b9d76939b70cd4d2f48f251R212) into a spot where it's hit by all non-timed-out code paths. I just have to make sure I can move it somewhere where sending on the closed channel won't cause a spurious panic. I'll try to have something up in a bit.

**Comment by tgross** [comment] 2016-10-20 14:47
I've opened https://github.com/joyent/containerpilot/pull/234. Again, thanks so much for including all the details like logs and the version in the bug report @commarla, that really helps me out in having a fast turnaround!

**Comment by commarla** [comment] 2016-10-20 18:41
Hi @tgross , I'm glad I could help. I'm gonna use containerpilot in every docker image I am building, it's the least I can do :P
Thanks @fitz123 for the help with my swarm cluster.

**Comment by tgross** [comment] 2016-10-28 15:12
Released as https://github.com/joyent/containerpilot/releases/tag/2.4.4

**Closed by tgross** 2016-10-28 15:12 UTC
Labels: awaiting release, bug
