### ISSUE TITLE
Support Consul TaggedAddresses

### ISSUE THREAD

**Issue by jacobloveless** [joyent/containerpilot#226] opened 2016-10-01 20:57 UTC
Hi all,
It looks like on service registration, we simply grab the local (private) IP address and use this for registering the service in consul. 
However for triton deployed containers, we should also push the Public facing IP (if any) into [TaggedAddress][wan] (from say `/native/usr/sbin/mdata-get sdc:nics |jq .[].ip` ?

```
# curl http://localhost:8500/v1/catalog/service/manager |jq
[
  {
    "Node": "673a28ec5a64",
    "Address": "192.168.128.125",
    "TaggedAddresses": {
      "lan": "192.168.128.125",
      **"wan": "192.168.128.125"  // it would be nice if was Triton public IP
    },
    "ServiceID": "manager-673a28ec5a64",
    "ServiceName": "manager",
    "ServiceTags": [
      "production",
      "managment"
    ],
    "ServiceAddress": "192.168.128.125",
    "ServicePort": 8080,
    "ServiceEnableTagOverride": false,
    "CreateIndex": 212,
    "ModifyIndex": 220
  }
]
```

**Comment by misterbisson** [comment] 2016-10-02 21:42
@jacobloveless You can select the IP address to advertise for a service with the `interfaces` spec in the service configuration. See https://www.joyent.com/containerpilot/docs/configuration for more details.

It doesn't appear that `TaggedAddresses` is part of the agent API as described in https://www.consul.io/docs/agent/http/agent.html#agent_service_register, but it definitely looks useful.

**Comment by tgross** [comment] 2016-10-03 12:48
@jacobloveless wrote:
> However for triton deployed containers, we should also push the Public facing IP (if any) into [TaggedAddress][wan] (from say /native/usr/sbin/mdata-get sdc:nics |jq .[].ip ?

We're intentionally avoiding Triton-specific configuration options.

@misterbisson wrote:
> It doesn't appear that TaggedAddresses is part of the agent API as described in https://www.consul.io/docs/agent/http/agent.html#agent_service_register, but it definitely looks useful.

It's not in the API documentation for the endpoint @jacobloveless is hitting here either: https://www.consul.io/docs/agent/http/catalog.html#catalog_service. What version of Consul do you have deployed?

**Comment by jacobloveless** [comment] 2016-10-04 14:46
0.7.0 - seems like there's a deficiency in the Service Registration there. I will circle back with Hashicorp.

**Comment by tgross** [comment] 2016-11-18 20:32
Updated the title of this to reflect the thing we want to do. With https://github.com/joyent/containerpilot/issues/243 and https://github.com/joyent/containerpilot/pull/248 we ideally would be able to support this but it looks like the Consul API library still doesn't support this field in [`AgentServiceRegistration`](https://godoc.org/github.com/hashicorp/consul/api#AgentServiceRegistration).

I'm going to create a new label `blocked` and assign it to this and call it an enhancement once upstream has a solution.

**Comment by tgross** [comment] 2017-01-27 14:07
Removing the `blocked` label as this is definitely in the docs now: https://godoc.org/github.com/hashicorp/consul/api#Node. When this gets implemented we may need to bump the version of the Consul library.

**Comment by tgross** [comment] 2017-06-15 17:16
Going to snag this as part of a batch of post-v3 Consul-related improvements.

**Comment by tgross** [comment] 2017-06-15 17:37
I'm reviewing this now and realizing that I failed to noticed that `TaggedAddresses` are not part of the agent spec, but part of the catalog spec. The way we're handling the problem is via the `interfaces` field and by having a Consul agent inside the container, in the case of Triton containers.

**Closed by tgross** 2017-06-15 17:37 UTC
Labels: enhancement, v3.x
