### ISSUE TITLE
'when:timeout' incorrectly terminates pipeline of jobs

### ISSUE THREAD

**Issue by wheleph** [joyent/containerpilot#456] opened 2017-08-01 14:18 UTC
It seems like `when:timeout` incorrectly terminates pipeline of jobs.

Here's my config file:

```
{
  consul: "localhost:8500",
  logging: {
    level: "DEBUG"
  },
  jobs: [
    {
      name: "job 1",
      exec: "echo === job 1 completed.",
      restarts: "never"
    },
    {
      name: "job 2",
      when: {
        source: "job 1",
        once: "exitSuccess",
        timeout: "10s"
      },
      exec: "/script.sh 2 100"
    }
  ]
}
```

Here `job 1` simulates a setup job which completes fast and `job 2` simulates a long-running service (`script.sh` just prints some info and sleeps for a given amount of seconds).

I expect that both jobs will complete successfully but that's not the case:

```
2017-08-01T13:55:28.703464146Z loaded config: {"Discovery":{},"LogConfig":{"level":"DEBUG","format":"default","output":"stdout"},"StopTimeout":5,"Jobs":[{"Name":"job 1","Exec":"echo === job 1 completed.","Port":0,"Interfaces":null,"Tags":null,"ConsulExtras":null,"Health":null,"ExecTimeout":"","Restarts":"never","StopTimeout":"","When":{"Frequency":"","Source":"","Once":"","Each":"","Timeout":""}},{"Name":"job 2","Exec":"/script.sh 2 100","Port":0,"Interfaces":null,"Tags":null,"ConsulExtras":null,"Health":null,"ExecTimeout":"","Restarts":null,"StopTimeout":"","When":{"Frequency":"","Source":"job 1","Once":"exitSuccess","Each":"","Timeout":"10s"}}],"Watches":null,"Telemetry":null,"Control":{"SocketPath":"/var/run/containerpilot.socket"}}
2017-08-01T13:55:28.703556436Z control: initialized router for control server
2017-08-01T13:55:28.703837501Z event: {Startup global}
2017-08-01T13:55:28.703912711Z control: serving at /var/run/containerpilot.socket
2017-08-01T13:55:28.704122161Z job 1.Run start
2017-08-01T13:55:28.705163619Z === job 1 completed.
2017-08-01T13:55:28.70519698Z job 1 exited without error
2017-08-01T13:55:28.705220352Z event: {ExitSuccess job 1}
2017-08-01T13:55:28.705251514Z job 1.Run end
2017-08-01T13:55:28.705284575Z job 1.term
2017-08-01T13:55:28.705294963Z terminating command 'job 1' at pid: 16
2017-08-01T13:55:28.705311743Z job 2.Run start
2017-08-01T13:55:28.705980445Z job exited but restart not permitted: job 1
2017-08-01T13:55:28.706037877Z event: {Stopping job 1}
2017-08-01T13:55:28.706077929Z event: {Stopped job 1}
2017-08-01T13:55:28.706827035Z === Containerpilot version:
2017-08-01T13:55:28.710607826Z Version: 3.3.1
2017-08-01T13:55:28.710630399Z GitHash: 98c0aba
2017-08-01T13:55:28.71115737Z === Starting script 2...
2017-08-01T13:55:38.70717674Z event: {TimerExpired job 2}
2017-08-01T13:55:38.707248954Z event: {Stopping job 2}
2017-08-01T13:55:38.707288507Z event: {Stopped job 2}
2017-08-01T13:55:38.707321767Z killing all processes in 5 seconds
2017-08-01T13:55:38.707544302Z job 2.term
2017-08-01T13:55:38.707587451Z terminating command 'job 2' at pid: 17
2017-08-01T13:55:38.708453318Z job 2 exited with error: signal: terminated
2017-08-01T13:55:38.708511448Z event: {ExitFailed job 2}
2017-08-01T13:55:38.708548205Z event: {Error job 2: signal: terminated}
2017-08-01T13:55:38.708584062Z job 2.Run end
2017-08-01T13:55:43.708557105Z killing processes for job "job 1"
2017-08-01T13:55:43.708605847Z job 1.kill
2017-08-01T13:55:43.708630318Z killing command 'job 1' at pid: 16
2017-08-01T13:55:43.708655887Z killing processes for job "job 2"
2017-08-01T13:55:43.708676762Z job 2.kill
2017-08-01T13:55:43.708709424Z killing command 'job 2' at pid: 17
```

As you can see `job 2` is terminated after 10 seconds.

Here are the rest of the helper files:

- script.sh:
```
#!/bin/sh

ID=$1
SLEEP=$2

echo "=== Containerpilot version:"
/opt/containerpilot/containerpilot --version
echo "=== Starting script $ID..."
sleep $SLEEP
echo "=== Completed script $ID"
```

- Dockerfile:
```
FROM centos:7

RUN mkdir -p /opt/containerpilot
COPY containerpilot-3.3.1 /opt/containerpilot/containerpilot
COPY app.json /opt/containerpilot/

COPY script.sh /script.sh
RUN chmod +x /script.sh

CMD /opt/containerpilot/containerpilot -config /opt/containerpilot/app.json
```

Is there a bug in containerpilot or is there some error in my configuration file?

**Comment by tgross** [comment] 2017-08-01 14:46
Thanks for the report @wheleph!

At first I thought that we'd messed up and passed the start timeout to the `exec`'s timeout, but I double-checked the code and [that doesn't seem to be the case](https://github.com/joyent/containerpilot/blob/fda54ab330c744fd959716bed816641e53f2f8e3/jobs/config.go#L244-L245).

When I dig into your logs a bit (and thank for providing debug logs up front!) it looks like there's a race between concurrent execution of `job 1` and `job 2`. The `job 1` starts, runs, and exits so fast that the event it fires lands before `job 2` ever gets a chance to start. Here's the relevant log section:

```
2017-08-01T13:55:28.704122161Z job 1.Run start
2017-08-01T13:55:28.705163619Z === job 1 completed.
2017-08-01T13:55:28.70519698Z job 1 exited without error
2017-08-01T13:55:28.705220352Z event: {ExitSuccess job 1}
2017-08-01T13:55:28.705251514Z job 1.Run end
2017-08-01T13:55:28.705284575Z job 1.term
2017-08-01T13:55:28.705294963Z terminating command 'job 1' at pid: 16
2017-08-01T13:55:28.705311743Z job 2.Run start
```

Note there is just over 1 millisecond between the time `job1.Run` starts and `job2.Run` starts, and `job1` is completing in that window. So `job1`'s execution is racing a [`for` loop](https://github.com/joyent/containerpilot/blob/fda54ab330c744fd959716bed816641e53f2f8e3/core/app.go#L151-L153) and winning. Narrowing the window of the race might be possible but there's not a lot of room to work with (and anything we do might be subject to the runtime throwing off timing anyways).

We might be able to fix this by moving the `Job.Subscribe()` call out of the `Job.Run()` method:

```
func (a *App) handlePolling() {
	for _, job := range a.Jobs {
		job.Subscribe(a.Bus)
		job.Bus = a.Bus
	}
	for _, job := range a.Jobs {
		job.Run(a.Bus)
	}
```

Because the `Rx` channel is buffered, we won't block the publishing of events but events that are published before all jobs are `Run()` will still be potentially interleaved between jobs. (They're still ordered within a single job's queue.)

So my take on this is that it _is_ a bug but it's also a very weird corner case you're unlikely to run into with real job configurations. I'll definitely fix it, but I also suspect you'll find it goes away if you have `job 1` do any work other than `echo`.

**Comment by tgross** [comment] 2017-08-01 15:02
I've smoke-tested this idea and it looks like it'll work so long as we don't receive 1000 events and blow up the buffers before the loop through all the jobs to call `Run` on them succeeds. The change breaks a bunch of tests though, so let me make sure those are just because we need to add a call to `Subscribe` for each of them and hopefully I'll have a PR up later today.

**Comment by ewjmulder** [comment] 2017-08-01 15:14
Hi @tgross. I'm a colleague of @wheleph. Some more clarification: the presented case is greatly simplified for the bug report. In the real case where we encountered this, the 'job1' actually did quite some work and it also happens. You can for example change the exec of job1 to be 'sleep 2' or so to test this.

I was jumping through the go codebase a bit in search for any clues. Indeed I suspected setting the when timeout on a exec timeout, but that is not the case as you pointed out above. But I can also not find any place where the timeout timer of the when timeout is canceled in case of receiving a 'exitSuccess'. Maybe that could be the issue?

**Comment by tgross** [comment] 2017-08-01 15:18
> But I can also not find any place where the timeout timer of the when timeout is canceled in case of receiving a 'exitSuccess'

Yup, that's it! Good catch! I'd adjusted the sleeps in the reproduction in my smoke test and if I hadn't done that I would've realized the `Subscribe` vs `Run` bit was a slight red herring. I've fixed that already here in my branch regardless, so lemme add the fix for the timeout and I think we'll be good to review a PR.

**Comment by tgross** [comment] 2017-08-01 15:27
Ok, with both fixes (and a 20 second rather than 200 second long 2nd script delay), I get logs that look like the following:

```
2017-08-01T11:25:27.609185616-04:00 event: {Startup global}
2017-08-01T11:25:27.609263305-04:00 control: serving at ./containerpilot.sock
2017-08-01T11:25:27.609359064-04:00 job 1.Run start
2017-08-01T11:25:27.613395171-04:00 === job 1 completed.
2017-08-01T11:25:27.613415958-04:00 job 1 exited without error
2017-08-01T11:25:27.613425385-04:00 event: {ExitSuccess job 1}
2017-08-01T11:25:27.613445168-04:00 job 1.Run end
2017-08-01T11:25:27.613460549-04:00 job 1.term
2017-08-01T11:25:27.613465488-04:00 terminating command 'job 1' at pid: 42979
2017-08-01T11:25:27.613474741-04:00 job exited but restart not permitted: job 1
2017-08-01T11:25:27.613480696-04:00 event: {Stopping job 1}
2017-08-01T11:25:27.613492379-04:00 event: {Stopped job 1}
2017-08-01T11:25:27.613500195-04:00 job 2.Run start
2017-08-01T11:25:27.628500681-04:00 === Containerpilot version:
2017-08-01T11:25:27.628520906-04:00 Version: dev-build-not-for-release
2017-08-01T11:25:27.628525384-04:00 GitHash: a618726
2017-08-01T11:25:27.628529331-04:00 === Starting script 2...
2017-08-01T11:25:47.631713707-04:00 === Completed script 2
2017-08-01T11:25:47.632043187-04:00 job 2 exited without error
2017-08-01T11:25:47.632065918-04:00 event: {ExitSuccess job 2}
2017-08-01T11:25:47.632096739-04:00 job 2.Run end
2017-08-01T11:25:47.632133612-04:00 job 2.term
2017-08-01T11:25:47.632142338-04:00 terminating command 'job 2' at pid: 42980
2017-08-01T11:25:47.632157479-04:00 job exited but restart not permitted: job 2
2017-08-01T11:25:47.632167468-04:00 event: {Stopping job 2}
2017-08-01T11:25:47.63219321-04:00 event: {Stopped job 2}
2017-08-01T11:25:47.632211318-04:00 killing all processes in 5 seconds
2017-08-01T11:25:52.636744158-04:00 killing processes for job "job 1"
2017-08-01T11:25:52.636809975-04:00 job 1.kill
2017-08-01T11:25:52.636832573-04:00 killing command 'job 1' at pid: 42979
2017-08-01T11:25:52.636898217-04:00 killing processes for job "job 2"
2017-08-01T11:25:52.636909623-04:00 job 2.kill
2017-08-01T11:25:52.636917037-04:00 killing command 'job 2' at pid: 42980
```

Running through the test suite now to make sure nothing got missed.

**Comment by ewjmulder** [comment] 2017-08-01 15:47
Great, thanks for the very quick response and fix! I tried to create a fix as well locally, but got lost in all the timer logic. So I'm curious to see the PR.
BTW: love your containerized makefile, works very nice and easy for a non-go-pro ;)

**Comment by wheleph** [comment] 2017-08-02 06:36
@tgross thank you for the lightning-fast fix!
@ewjmulder thank you for stepping in!

**Comment by tgross** [comment] 2017-08-02 12:12
Released in https://github.com/joyent/containerpilot/releases/tag/3.3.2. Thanks for the bug report and help in debugging, folks!

**Closed by tgross** 2017-08-02 12:12 UTC
Labels: fixed, released, v3.x
