### ISSUE TITLE
Expose ContainerPilot details as env vars for other apps to consume

### ISSUE THREAD

**Issue by misterbisson** [joyent/containerpilot#145] opened 2016-05-08 18:46 UTC
There are times when it would be very useful to share ContainerPilot configuration details (and the details it resolves) with the "main" application. The ContainerPiliot-advertised IP addresses for the registered services are one example that would be useful for some apps, so we can make sure they listen on the same interface that ContainerPilot thinks they are.

This usage example addresses Consul startup when there are multiple interfaces with RFC1918 IP addresses:

```yaml
  command: >
    /opt/containerpilot/containerpilot
      /bin/consul agent -server
        -config-dir=/config
        -ui-dir /ui
        -advertise ${CONTAINERPILOT_SERVICE_CONSUL_IP} \
        -bootstrap-expect 3
```

The Consul issue is further described in https://github.com/autopilotpattern/consul/issues/17

**Comment by tgross** [comment] 2016-05-09 13:05
The particular syntax we have here won't work, because Compose would interpolate that variable before it ever makes it into the container. But I suspect we can get away with allowing golang template syntax (so long as Docker doesn't decide to use that in the future in lieu of shell env var style). We'd then want to create those environment variables by overriding [`os/exec.Cmd.Env`](https://golang.org/pkg/os/exec/#Cmd) when we fork the process.

Design questions/issues:
- What variables do we want to expose?
- If the variables are named dynamically, which this proposal seems to suggest, what naming convention should those variables use?
- I don't know of any mechanism to update the environment variables of the child process after we fork (outside of non-portable `mdb` wizardry), which means if we update the ContainerPilot config then the environment variables in the child process won't be updated.
- We should not replace the `Env` slice entirely, but instead append the new environment variables to the parent's (i.e. ContainerPilot's) environment variables. Otherwise env vars set via `-e` flags on `docker run` and the Compose equivalent will be erased, which would be unexpected behavior.

**Comment by misterbisson** [comment] 2016-05-12 04:53
Good questions @tgross 

> We should not replace the Env slice entirely, but instead append the new environment variables

Agreed.

> I don't know of any mechanism to update the environment variables of the child process after we fork 

Very fair point, and an acceptable limitation, I think.

> The particular syntax we have here won't work... But I suspect we can get away with allowing golang template syntax

Very good point, and one of the frustrations at the heart of the underlying issue. Golang template syntax should be a fair and workable alternative, however.

> What variables do we want to expose... what naming convention?

This needs more thought.

I need to cast about for more use cases so we can better understand the problem before diving in.

**Comment by justenwalker** [comment] 2016-05-13 01:17
With golang templates, I think we can provide a mechanism for looking up app-state information. With a bit of tweaking we could do something like [consul-template](https://github.com/hashicorp/consul-template)

```
 /opt/containerpilot/containerpilot
   /bin/consul agent -server \
     -config-dir=/config \
     -ui-dir /ui \
     -advertise { interface "eth0:inet" } \
     -bootstrap-expect 3
```

Possibly we could expose an "ENV" section in the containerpilot config which is loaded just before running any commands

```json
{
  "env": {
    "MY_ENV_VAR": "{ interface \"192.168.0.0/16\" }"
  }
}
```

Limitation is still that reload will not change the environment or the command.

**Comment by tgross** [comment] 2016-05-13 12:07
> With a bit of tweaking we could do something like consul-template

This is the ever-so-slightly-crazy kind of idea I like. 😀 

I was *almost* about to say "why not just use consul-template's code as a library?" but then I realized that wouldn't fly with non-Consul backends. I feel like this expands the scope of the issue a bit though. Maybe a first pass implementation would be to interpolate environment variables before we take a run at something like adding template tags.

> I'm unsure if we want to pre-process these template env variables along with the rest of the golang templates we currently support, or after the config is loaded (multi-pass). The latter means they'd have to be escaped or otherwise not the same delimiter that golang uses by default. 

I agree -- multi-pass* is going to add complications from escaping. I think this would become an area ripe for end-user error. Common Docker deployment scenarios already involve the user having to deal with bash variables or Docker Compose variables as it is.


```

* <leelo>"muuuuul-tiii-pass"</leelo>
```

**Comment by tgross** [comment] 2016-06-01 16:43
PR open: https://github.com/joyent/containerpilot/pull/170

**Comment by tgross** [comment] 2016-06-01 16:46
Note that the open PR is basically just the "first pass" version of this, where we are able to get stuff from the environment. Ideally in the long run we'd like to do something like what @justenwalker has suggested where we have a richer `consul-template`-like templating available.

**Comment by tgross** [comment] 2016-06-01 17:13
Released in https://github.com/joyent/containerpilot/releases/tag/2.1.4.

@misterbisson @justenwalker do we want to close this particular issue and revisit the notion of doing more complex templating later, or just leave this open?

**Comment by justenwalker** [comment] 2016-06-01 17:35
@tgross I think the initial point of this issue was just for environment variable interpolation.  We probably want a new ticket to track the `consul-template`-like interpolation feature

**Comment by tgross** [comment] 2016-06-01 17:41
Sounds good to me. I'll open a new issue.

**Closed by tgross** 2016-06-01 17:41 UTC
Labels: enhancement, released
